/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Adresse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Adresse'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.ADRKontaktRequest = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Adresse);
  }
}(this, function(ApiClient, Adresse) {
  'use strict';




  /**
   * The ADRKontaktRequest model module.
   * @module model/ADRKontaktRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>ADRKontaktRequest</code>.
   * @alias module:model/ADRKontaktRequest
   * @class
   * @param adresse {module:model/Adresse} 
   * @param name {String} 
   * @param PLZ {String} 
   * @param ort {String} 
   */
  var exports = function(adresse, name, PLZ, ort) {
    var _this = this;

    _this['Adresse'] = adresse;
    _this['Name'] = name;
    _this['PLZ'] = PLZ;
    _this['Ort'] = ort;
  };

  /**
   * Constructs a <code>ADRKontaktRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ADRKontaktRequest} obj Optional instance to populate.
   * @return {module:model/ADRKontaktRequest} The populated <code>ADRKontaktRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Adresse')) {
        obj['Adresse'] = Adresse.constructFromObject(data['Adresse']);
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('PLZ')) {
        obj['PLZ'] = ApiClient.convertToType(data['PLZ'], 'String');
      }
      if (data.hasOwnProperty('Ort')) {
        obj['Ort'] = ApiClient.convertToType(data['Ort'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Adresse} Adresse
   */
  exports.prototype['Adresse'] = undefined;
  /**
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * @member {String} PLZ
   */
  exports.prototype['PLZ'] = undefined;
  /**
   * @member {String} Ort
   */
  exports.prototype['Ort'] = undefined;



  return exports;
}));


