/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Adresse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Adresse'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.ADRZahlungsartZahlungsartNr = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Adresse);
  }
}(this, function(ApiClient, Adresse) {
  'use strict';




  /**
   * The ADRZahlungsartZahlungsartNr model module.
   * @module model/ADRZahlungsartZahlungsartNr
   * @version 1.0
   */

  /**
   * Constructs a new <code>ADRZahlungsartZahlungsartNr</code>.
   * @alias module:model/ADRZahlungsartZahlungsartNr
   * @class
   * @param zahlungsartNr {Number} 
   * @param adresse {module:model/Adresse} 
   * @param bankBelegNummer {Number} 
   * @param bank {String} 
   * @param beguenstigter {String} 
   * @param belastenVon {String} 
   * @param eigeneZahlungsart {Boolean} 
   * @param formCode {String} 
   * @param hauptZahlungsart {Boolean} 
   * @param inaktiv {Boolean} 
   * @param kontonummerBank {String} 
   * @param konto {String} 
   * @param postcheckNummer {String} 
   * @param spesenregelung {Number} 
   * @param swiftNummer {String} 
   * @param teilnehmerNummer {String} 
   * @param zahlArt {Number} 
   * @param zahlungsartTyp {String} 
   * @param bemerkungen {String} 
   * @param erstelltAm {String} 
   * @param erstelltVon {String} 
   * @param geaendertAm {String} 
   * @param geaendertVon {String} 
   * @param zusatzfelder {Object} 
   */
  var exports = function(zahlungsartNr, adresse, bankBelegNummer, bank, beguenstigter, belastenVon, eigeneZahlungsart, formCode, hauptZahlungsart, inaktiv, kontonummerBank, konto, postcheckNummer, spesenregelung, swiftNummer, teilnehmerNummer, zahlArt, zahlungsartTyp, bemerkungen, erstelltAm, erstelltVon, geaendertAm, geaendertVon, zusatzfelder) {
    var _this = this;

    _this['ZahlungsartNr'] = zahlungsartNr;
    _this['Adresse'] = adresse;
    _this['BankBelegNummer'] = bankBelegNummer;
    _this['Bank'] = bank;
    _this['Beguenstigter'] = beguenstigter;
    _this['BelastenVon'] = belastenVon;
    _this['EigeneZahlungsart'] = eigeneZahlungsart;
    _this['FormCode'] = formCode;
    _this['HauptZahlungsart'] = hauptZahlungsart;
    _this['Inaktiv'] = inaktiv;
    _this['KontonummerBank'] = kontonummerBank;
    _this['Konto'] = konto;
    _this['PostcheckNummer'] = postcheckNummer;
    _this['Spesenregelung'] = spesenregelung;
    _this['SwiftNummer'] = swiftNummer;
    _this['TeilnehmerNummer'] = teilnehmerNummer;
    _this['ZahlArt'] = zahlArt;
    _this['ZahlungsartTyp'] = zahlungsartTyp;
    _this['Bemerkungen'] = bemerkungen;
    _this['ErstelltAm'] = erstelltAm;
    _this['ErstelltVon'] = erstelltVon;
    _this['GeaendertAm'] = geaendertAm;
    _this['GeaendertVon'] = geaendertVon;
    _this['Zusatzfelder'] = zusatzfelder;
  };

  /**
   * Constructs a <code>ADRZahlungsartZahlungsartNr</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ADRZahlungsartZahlungsartNr} obj Optional instance to populate.
   * @return {module:model/ADRZahlungsartZahlungsartNr} The populated <code>ADRZahlungsartZahlungsartNr</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ZahlungsartNr')) {
        obj['ZahlungsartNr'] = ApiClient.convertToType(data['ZahlungsartNr'], 'Number');
      }
      if (data.hasOwnProperty('Adresse')) {
        obj['Adresse'] = Adresse.constructFromObject(data['Adresse']);
      }
      if (data.hasOwnProperty('BankBelegNummer')) {
        obj['BankBelegNummer'] = ApiClient.convertToType(data['BankBelegNummer'], 'Number');
      }
      if (data.hasOwnProperty('Bank')) {
        obj['Bank'] = ApiClient.convertToType(data['Bank'], 'String');
      }
      if (data.hasOwnProperty('Beguenstigter')) {
        obj['Beguenstigter'] = ApiClient.convertToType(data['Beguenstigter'], 'String');
      }
      if (data.hasOwnProperty('BelastenVon')) {
        obj['BelastenVon'] = ApiClient.convertToType(data['BelastenVon'], 'String');
      }
      if (data.hasOwnProperty('EigeneZahlungsart')) {
        obj['EigeneZahlungsart'] = ApiClient.convertToType(data['EigeneZahlungsart'], 'Boolean');
      }
      if (data.hasOwnProperty('FormCode')) {
        obj['FormCode'] = ApiClient.convertToType(data['FormCode'], 'String');
      }
      if (data.hasOwnProperty('HauptZahlungsart')) {
        obj['HauptZahlungsart'] = ApiClient.convertToType(data['HauptZahlungsart'], 'Boolean');
      }
      if (data.hasOwnProperty('Inaktiv')) {
        obj['Inaktiv'] = ApiClient.convertToType(data['Inaktiv'], 'Boolean');
      }
      if (data.hasOwnProperty('KontonummerBank')) {
        obj['KontonummerBank'] = ApiClient.convertToType(data['KontonummerBank'], 'String');
      }
      if (data.hasOwnProperty('Konto')) {
        obj['Konto'] = ApiClient.convertToType(data['Konto'], 'String');
      }
      if (data.hasOwnProperty('PostcheckNummer')) {
        obj['PostcheckNummer'] = ApiClient.convertToType(data['PostcheckNummer'], 'String');
      }
      if (data.hasOwnProperty('Spesenregelung')) {
        obj['Spesenregelung'] = ApiClient.convertToType(data['Spesenregelung'], 'Number');
      }
      if (data.hasOwnProperty('SwiftNummer')) {
        obj['SwiftNummer'] = ApiClient.convertToType(data['SwiftNummer'], 'String');
      }
      if (data.hasOwnProperty('TeilnehmerNummer')) {
        obj['TeilnehmerNummer'] = ApiClient.convertToType(data['TeilnehmerNummer'], 'String');
      }
      if (data.hasOwnProperty('ZahlArt')) {
        obj['ZahlArt'] = ApiClient.convertToType(data['ZahlArt'], 'Number');
      }
      if (data.hasOwnProperty('ZahlungsartTyp')) {
        obj['ZahlungsartTyp'] = ApiClient.convertToType(data['ZahlungsartTyp'], 'String');
      }
      if (data.hasOwnProperty('Bemerkungen')) {
        obj['Bemerkungen'] = ApiClient.convertToType(data['Bemerkungen'], 'String');
      }
      if (data.hasOwnProperty('ErstelltAm')) {
        obj['ErstelltAm'] = ApiClient.convertToType(data['ErstelltAm'], 'String');
      }
      if (data.hasOwnProperty('ErstelltVon')) {
        obj['ErstelltVon'] = ApiClient.convertToType(data['ErstelltVon'], 'String');
      }
      if (data.hasOwnProperty('GeaendertAm')) {
        obj['GeaendertAm'] = ApiClient.convertToType(data['GeaendertAm'], 'String');
      }
      if (data.hasOwnProperty('GeaendertVon')) {
        obj['GeaendertVon'] = ApiClient.convertToType(data['GeaendertVon'], 'String');
      }
      if (data.hasOwnProperty('Zusatzfelder')) {
        obj['Zusatzfelder'] = ApiClient.convertToType(data['Zusatzfelder'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Number} ZahlungsartNr
   */
  exports.prototype['ZahlungsartNr'] = undefined;
  /**
   * @member {module:model/Adresse} Adresse
   */
  exports.prototype['Adresse'] = undefined;
  /**
   * @member {Number} BankBelegNummer
   */
  exports.prototype['BankBelegNummer'] = undefined;
  /**
   * @member {String} Bank
   */
  exports.prototype['Bank'] = undefined;
  /**
   * @member {String} Beguenstigter
   */
  exports.prototype['Beguenstigter'] = undefined;
  /**
   * @member {String} BelastenVon
   */
  exports.prototype['BelastenVon'] = undefined;
  /**
   * @member {Boolean} EigeneZahlungsart
   */
  exports.prototype['EigeneZahlungsart'] = undefined;
  /**
   * @member {String} FormCode
   */
  exports.prototype['FormCode'] = undefined;
  /**
   * @member {Boolean} HauptZahlungsart
   */
  exports.prototype['HauptZahlungsart'] = undefined;
  /**
   * @member {Boolean} Inaktiv
   */
  exports.prototype['Inaktiv'] = undefined;
  /**
   * @member {String} KontonummerBank
   */
  exports.prototype['KontonummerBank'] = undefined;
  /**
   * @member {String} Konto
   */
  exports.prototype['Konto'] = undefined;
  /**
   * @member {String} PostcheckNummer
   */
  exports.prototype['PostcheckNummer'] = undefined;
  /**
   * @member {Number} Spesenregelung
   */
  exports.prototype['Spesenregelung'] = undefined;
  /**
   * @member {String} SwiftNummer
   */
  exports.prototype['SwiftNummer'] = undefined;
  /**
   * @member {String} TeilnehmerNummer
   */
  exports.prototype['TeilnehmerNummer'] = undefined;
  /**
   * @member {Number} ZahlArt
   */
  exports.prototype['ZahlArt'] = undefined;
  /**
   * @member {String} ZahlungsartTyp
   */
  exports.prototype['ZahlungsartTyp'] = undefined;
  /**
   * @member {String} Bemerkungen
   */
  exports.prototype['Bemerkungen'] = undefined;
  /**
   * @member {String} ErstelltAm
   */
  exports.prototype['ErstelltAm'] = undefined;
  /**
   * @member {String} ErstelltVon
   */
  exports.prototype['ErstelltVon'] = undefined;
  /**
   * @member {String} GeaendertAm
   */
  exports.prototype['GeaendertAm'] = undefined;
  /**
   * @member {String} GeaendertVon
   */
  exports.prototype['GeaendertVon'] = undefined;
  /**
   * @member {Object} Zusatzfelder
   */
  exports.prototype['Zusatzfelder'] = undefined;



  return exports;
}));


