/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Kontoklasse1', 'model/Steuercode8', 'model/Waehrung7'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Kontoklasse1'), require('./Steuercode8'), require('./Waehrung7'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.Aufwandskonto = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Kontoklasse1, root.ProffixRestApiRequestSammlung.Steuercode8, root.ProffixRestApiRequestSammlung.Waehrung7);
  }
}(this, function(ApiClient, Kontoklasse1, Steuercode8, Waehrung7) {
  'use strict';




  /**
   * The Aufwandskonto model module.
   * @module model/Aufwandskonto
   * @version 1.0
   */

  /**
   * Constructs a new <code>Aufwandskonto</code>.
   * @alias module:model/Aufwandskonto
   * @class
   * @param kontoNr {String} 
   * @param bezeichnung {String} 
   * @param steuercode {module:model/Steuercode8} 
   * @param kontoklasse {module:model/Kontoklasse1} 
   * @param kostenstelle {String} 
   * @param kostenstelleZwingend {Number} 
   * @param kostenstelleFix {Boolean} 
   * @param kostenart {String} 
   * @param kostenartZwingend {Number} 
   * @param kostenartFix {Boolean} 
   * @param waehrung {module:model/Waehrung7} 
   * @param auftrag {String} 
   * @param auftragZwingend {Number} 
   * @param auftragFix {Boolean} 
   * @param lohnart {String} 
   * @param lohnartZwingend {Number} 
   * @param lohnartFix {Boolean} 
   * @param buchenInFinanzbuchhaltung {Boolean} 
   * @param buchenInDebitorenbuchhaltung {Boolean} 
   * @param buchenInKreditorenbuchhaltung {Boolean} 
   * @param buchenInAuftragsbearbeitung {Boolean} 
   * @param buchenInLeistungsverwaltung {Boolean} 
   * @param buchenInAnlagekonto {Boolean} 
   * @param sperre {String} 
   * @param erstelltAm {String} 
   * @param erstelltVon {String} 
   * @param geaendertAm {String} 
   * @param geaendertVon {String} 
   * @param zusatzfelder {Object} 
   */
  var exports = function(kontoNr, bezeichnung, steuercode, kontoklasse, kostenstelle, kostenstelleZwingend, kostenstelleFix, kostenart, kostenartZwingend, kostenartFix, waehrung, auftrag, auftragZwingend, auftragFix, lohnart, lohnartZwingend, lohnartFix, buchenInFinanzbuchhaltung, buchenInDebitorenbuchhaltung, buchenInKreditorenbuchhaltung, buchenInAuftragsbearbeitung, buchenInLeistungsverwaltung, buchenInAnlagekonto, sperre, erstelltAm, erstelltVon, geaendertAm, geaendertVon, zusatzfelder) {
    var _this = this;

    _this['KontoNr'] = kontoNr;
    _this['Bezeichnung'] = bezeichnung;
    _this['Steuercode'] = steuercode;
    _this['Kontoklasse'] = kontoklasse;
    _this['Kostenstelle'] = kostenstelle;
    _this['KostenstelleZwingend'] = kostenstelleZwingend;
    _this['KostenstelleFix'] = kostenstelleFix;
    _this['Kostenart'] = kostenart;
    _this['KostenartZwingend'] = kostenartZwingend;
    _this['KostenartFix'] = kostenartFix;
    _this['Waehrung'] = waehrung;
    _this['Auftrag'] = auftrag;
    _this['AuftragZwingend'] = auftragZwingend;
    _this['AuftragFix'] = auftragFix;
    _this['Lohnart'] = lohnart;
    _this['LohnartZwingend'] = lohnartZwingend;
    _this['LohnartFix'] = lohnartFix;
    _this['BuchenInFinanzbuchhaltung'] = buchenInFinanzbuchhaltung;
    _this['BuchenInDebitorenbuchhaltung'] = buchenInDebitorenbuchhaltung;
    _this['BuchenInKreditorenbuchhaltung'] = buchenInKreditorenbuchhaltung;
    _this['BuchenInAuftragsbearbeitung'] = buchenInAuftragsbearbeitung;
    _this['BuchenInLeistungsverwaltung'] = buchenInLeistungsverwaltung;
    _this['BuchenInAnlagekonto'] = buchenInAnlagekonto;
    _this['Sperre'] = sperre;
    _this['ErstelltAm'] = erstelltAm;
    _this['ErstelltVon'] = erstelltVon;
    _this['GeaendertAm'] = geaendertAm;
    _this['GeaendertVon'] = geaendertVon;
    _this['Zusatzfelder'] = zusatzfelder;
  };

  /**
   * Constructs a <code>Aufwandskonto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Aufwandskonto} obj Optional instance to populate.
   * @return {module:model/Aufwandskonto} The populated <code>Aufwandskonto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('KontoNr')) {
        obj['KontoNr'] = ApiClient.convertToType(data['KontoNr'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung')) {
        obj['Bezeichnung'] = ApiClient.convertToType(data['Bezeichnung'], 'String');
      }
      if (data.hasOwnProperty('Steuercode')) {
        obj['Steuercode'] = Steuercode8.constructFromObject(data['Steuercode']);
      }
      if (data.hasOwnProperty('Kontoklasse')) {
        obj['Kontoklasse'] = Kontoklasse1.constructFromObject(data['Kontoklasse']);
      }
      if (data.hasOwnProperty('Kostenstelle')) {
        obj['Kostenstelle'] = ApiClient.convertToType(data['Kostenstelle'], 'String');
      }
      if (data.hasOwnProperty('KostenstelleZwingend')) {
        obj['KostenstelleZwingend'] = ApiClient.convertToType(data['KostenstelleZwingend'], 'Number');
      }
      if (data.hasOwnProperty('KostenstelleFix')) {
        obj['KostenstelleFix'] = ApiClient.convertToType(data['KostenstelleFix'], 'Boolean');
      }
      if (data.hasOwnProperty('Kostenart')) {
        obj['Kostenart'] = ApiClient.convertToType(data['Kostenart'], 'String');
      }
      if (data.hasOwnProperty('KostenartZwingend')) {
        obj['KostenartZwingend'] = ApiClient.convertToType(data['KostenartZwingend'], 'Number');
      }
      if (data.hasOwnProperty('KostenartFix')) {
        obj['KostenartFix'] = ApiClient.convertToType(data['KostenartFix'], 'Boolean');
      }
      if (data.hasOwnProperty('Waehrung')) {
        obj['Waehrung'] = Waehrung7.constructFromObject(data['Waehrung']);
      }
      if (data.hasOwnProperty('Auftrag')) {
        obj['Auftrag'] = ApiClient.convertToType(data['Auftrag'], 'String');
      }
      if (data.hasOwnProperty('AuftragZwingend')) {
        obj['AuftragZwingend'] = ApiClient.convertToType(data['AuftragZwingend'], 'Number');
      }
      if (data.hasOwnProperty('AuftragFix')) {
        obj['AuftragFix'] = ApiClient.convertToType(data['AuftragFix'], 'Boolean');
      }
      if (data.hasOwnProperty('Lohnart')) {
        obj['Lohnart'] = ApiClient.convertToType(data['Lohnart'], 'String');
      }
      if (data.hasOwnProperty('LohnartZwingend')) {
        obj['LohnartZwingend'] = ApiClient.convertToType(data['LohnartZwingend'], 'Number');
      }
      if (data.hasOwnProperty('LohnartFix')) {
        obj['LohnartFix'] = ApiClient.convertToType(data['LohnartFix'], 'Boolean');
      }
      if (data.hasOwnProperty('BuchenInFinanzbuchhaltung')) {
        obj['BuchenInFinanzbuchhaltung'] = ApiClient.convertToType(data['BuchenInFinanzbuchhaltung'], 'Boolean');
      }
      if (data.hasOwnProperty('BuchenInDebitorenbuchhaltung')) {
        obj['BuchenInDebitorenbuchhaltung'] = ApiClient.convertToType(data['BuchenInDebitorenbuchhaltung'], 'Boolean');
      }
      if (data.hasOwnProperty('BuchenInKreditorenbuchhaltung')) {
        obj['BuchenInKreditorenbuchhaltung'] = ApiClient.convertToType(data['BuchenInKreditorenbuchhaltung'], 'Boolean');
      }
      if (data.hasOwnProperty('BuchenInAuftragsbearbeitung')) {
        obj['BuchenInAuftragsbearbeitung'] = ApiClient.convertToType(data['BuchenInAuftragsbearbeitung'], 'Boolean');
      }
      if (data.hasOwnProperty('BuchenInLeistungsverwaltung')) {
        obj['BuchenInLeistungsverwaltung'] = ApiClient.convertToType(data['BuchenInLeistungsverwaltung'], 'Boolean');
      }
      if (data.hasOwnProperty('BuchenInAnlagekonto')) {
        obj['BuchenInAnlagekonto'] = ApiClient.convertToType(data['BuchenInAnlagekonto'], 'Boolean');
      }
      if (data.hasOwnProperty('Sperre')) {
        obj['Sperre'] = ApiClient.convertToType(data['Sperre'], 'String');
      }
      if (data.hasOwnProperty('ErstelltAm')) {
        obj['ErstelltAm'] = ApiClient.convertToType(data['ErstelltAm'], 'String');
      }
      if (data.hasOwnProperty('ErstelltVon')) {
        obj['ErstelltVon'] = ApiClient.convertToType(data['ErstelltVon'], 'String');
      }
      if (data.hasOwnProperty('GeaendertAm')) {
        obj['GeaendertAm'] = ApiClient.convertToType(data['GeaendertAm'], 'String');
      }
      if (data.hasOwnProperty('GeaendertVon')) {
        obj['GeaendertVon'] = ApiClient.convertToType(data['GeaendertVon'], 'String');
      }
      if (data.hasOwnProperty('Zusatzfelder')) {
        obj['Zusatzfelder'] = ApiClient.convertToType(data['Zusatzfelder'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} KontoNr
   */
  exports.prototype['KontoNr'] = undefined;
  /**
   * @member {String} Bezeichnung
   */
  exports.prototype['Bezeichnung'] = undefined;
  /**
   * @member {module:model/Steuercode8} Steuercode
   */
  exports.prototype['Steuercode'] = undefined;
  /**
   * @member {module:model/Kontoklasse1} Kontoklasse
   */
  exports.prototype['Kontoklasse'] = undefined;
  /**
   * @member {String} Kostenstelle
   */
  exports.prototype['Kostenstelle'] = undefined;
  /**
   * @member {Number} KostenstelleZwingend
   */
  exports.prototype['KostenstelleZwingend'] = undefined;
  /**
   * @member {Boolean} KostenstelleFix
   */
  exports.prototype['KostenstelleFix'] = undefined;
  /**
   * @member {String} Kostenart
   */
  exports.prototype['Kostenart'] = undefined;
  /**
   * @member {Number} KostenartZwingend
   */
  exports.prototype['KostenartZwingend'] = undefined;
  /**
   * @member {Boolean} KostenartFix
   */
  exports.prototype['KostenartFix'] = undefined;
  /**
   * @member {module:model/Waehrung7} Waehrung
   */
  exports.prototype['Waehrung'] = undefined;
  /**
   * @member {String} Auftrag
   */
  exports.prototype['Auftrag'] = undefined;
  /**
   * @member {Number} AuftragZwingend
   */
  exports.prototype['AuftragZwingend'] = undefined;
  /**
   * @member {Boolean} AuftragFix
   */
  exports.prototype['AuftragFix'] = undefined;
  /**
   * @member {String} Lohnart
   */
  exports.prototype['Lohnart'] = undefined;
  /**
   * @member {Number} LohnartZwingend
   */
  exports.prototype['LohnartZwingend'] = undefined;
  /**
   * @member {Boolean} LohnartFix
   */
  exports.prototype['LohnartFix'] = undefined;
  /**
   * @member {Boolean} BuchenInFinanzbuchhaltung
   */
  exports.prototype['BuchenInFinanzbuchhaltung'] = undefined;
  /**
   * @member {Boolean} BuchenInDebitorenbuchhaltung
   */
  exports.prototype['BuchenInDebitorenbuchhaltung'] = undefined;
  /**
   * @member {Boolean} BuchenInKreditorenbuchhaltung
   */
  exports.prototype['BuchenInKreditorenbuchhaltung'] = undefined;
  /**
   * @member {Boolean} BuchenInAuftragsbearbeitung
   */
  exports.prototype['BuchenInAuftragsbearbeitung'] = undefined;
  /**
   * @member {Boolean} BuchenInLeistungsverwaltung
   */
  exports.prototype['BuchenInLeistungsverwaltung'] = undefined;
  /**
   * @member {Boolean} BuchenInAnlagekonto
   */
  exports.prototype['BuchenInAnlagekonto'] = undefined;
  /**
   * @member {String} Sperre
   */
  exports.prototype['Sperre'] = undefined;
  /**
   * @member {String} ErstelltAm
   */
  exports.prototype['ErstelltAm'] = undefined;
  /**
   * @member {String} ErstelltVon
   */
  exports.prototype['ErstelltVon'] = undefined;
  /**
   * @member {String} GeaendertAm
   */
  exports.prototype['GeaendertAm'] = undefined;
  /**
   * @member {String} GeaendertVon
   */
  exports.prototype['GeaendertVon'] = undefined;
  /**
   * @member {Object} Zusatzfelder
   */
  exports.prototype['Zusatzfelder'] = undefined;



  return exports;
}));


