/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Steuercode1', 'model/SteuercodeEinkauf1'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Steuercode1'), require('./SteuercodeEinkauf1'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.LAGArtikelRequest = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Steuercode1, root.ProffixRestApiRequestSammlung.SteuercodeEinkauf1);
  }
}(this, function(ApiClient, Steuercode1, SteuercodeEinkauf1) {
  'use strict';




  /**
   * The LAGArtikelRequest model module.
   * @module model/LAGArtikelRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>LAGArtikelRequest</code>.
   * @alias module:model/LAGArtikelRequest
   * @class
   * @param artikelNr {String} 
   * @param bezeichnung1 {String} 
   * @param bezeichnung2 {String} 
   * @param steuercode {module:model/Steuercode1} 
   * @param steuercodeEinkauf {module:model/SteuercodeEinkauf1} 
   */
  var exports = function(artikelNr, bezeichnung1, bezeichnung2, steuercode, steuercodeEinkauf) {
    var _this = this;

    _this['ArtikelNr'] = artikelNr;
    _this['Bezeichnung1'] = bezeichnung1;
    _this['Bezeichnung2'] = bezeichnung2;
    _this['Steuercode'] = steuercode;
    _this['SteuercodeEinkauf'] = steuercodeEinkauf;
  };

  /**
   * Constructs a <code>LAGArtikelRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LAGArtikelRequest} obj Optional instance to populate.
   * @return {module:model/LAGArtikelRequest} The populated <code>LAGArtikelRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ArtikelNr')) {
        obj['ArtikelNr'] = ApiClient.convertToType(data['ArtikelNr'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung1')) {
        obj['Bezeichnung1'] = ApiClient.convertToType(data['Bezeichnung1'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung2')) {
        obj['Bezeichnung2'] = ApiClient.convertToType(data['Bezeichnung2'], 'String');
      }
      if (data.hasOwnProperty('Steuercode')) {
        obj['Steuercode'] = Steuercode1.constructFromObject(data['Steuercode']);
      }
      if (data.hasOwnProperty('SteuercodeEinkauf')) {
        obj['SteuercodeEinkauf'] = SteuercodeEinkauf1.constructFromObject(data['SteuercodeEinkauf']);
      }
    }
    return obj;
  }

  /**
   * @member {String} ArtikelNr
   */
  exports.prototype['ArtikelNr'] = undefined;
  /**
   * @member {String} Bezeichnung1
   */
  exports.prototype['Bezeichnung1'] = undefined;
  /**
   * @member {String} Bezeichnung2
   */
  exports.prototype['Bezeichnung2'] = undefined;
  /**
   * @member {module:model/Steuercode1} Steuercode
   */
  exports.prototype['Steuercode'] = undefined;
  /**
   * @member {module:model/SteuercodeEinkauf1} SteuercodeEinkauf
   */
  exports.prototype['SteuercodeEinkauf'] = undefined;



  return exports;
}));


