/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Lagerort', 'model/LagerortNach', 'model/Lagerplatz', 'model/LagerplatzNach'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Lagerort'), require('./LagerortNach'), require('./Lagerplatz'), require('./LagerplatzNach'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.Lagerbewegungen1 = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Lagerort, root.ProffixRestApiRequestSammlung.LagerortNach, root.ProffixRestApiRequestSammlung.Lagerplatz, root.ProffixRestApiRequestSammlung.LagerplatzNach);
  }
}(this, function(ApiClient, Lagerort, LagerortNach, Lagerplatz, LagerplatzNach) {
  'use strict';




  /**
   * The Lagerbewegungen1 model module.
   * @module model/Lagerbewegungen1
   * @version 1.0
   */

  /**
   * Constructs a new <code>Lagerbewegungen1</code>.
   * @alias module:model/Lagerbewegungen1
   * @class
   * @param menge {Number} 
   * @param lagerort {module:model/Lagerort} 
   * @param lagerplatz {module:model/Lagerplatz} 
   * @param lagerortNach {module:model/LagerortNach} 
   * @param lagerplatzNach {module:model/LagerplatzNach} 
   */
  var exports = function(menge, lagerort, lagerplatz, lagerortNach, lagerplatzNach) {
    var _this = this;

    _this['Menge'] = menge;
    _this['Lagerort'] = lagerort;
    _this['Lagerplatz'] = lagerplatz;
    _this['LagerortNach'] = lagerortNach;
    _this['LagerplatzNach'] = lagerplatzNach;
  };

  /**
   * Constructs a <code>Lagerbewegungen1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Lagerbewegungen1} obj Optional instance to populate.
   * @return {module:model/Lagerbewegungen1} The populated <code>Lagerbewegungen1</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Menge')) {
        obj['Menge'] = ApiClient.convertToType(data['Menge'], 'Number');
      }
      if (data.hasOwnProperty('Lagerort')) {
        obj['Lagerort'] = Lagerort.constructFromObject(data['Lagerort']);
      }
      if (data.hasOwnProperty('Lagerplatz')) {
        obj['Lagerplatz'] = Lagerplatz.constructFromObject(data['Lagerplatz']);
      }
      if (data.hasOwnProperty('LagerortNach')) {
        obj['LagerortNach'] = LagerortNach.constructFromObject(data['LagerortNach']);
      }
      if (data.hasOwnProperty('LagerplatzNach')) {
        obj['LagerplatzNach'] = LagerplatzNach.constructFromObject(data['LagerplatzNach']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} Menge
   */
  exports.prototype['Menge'] = undefined;
  /**
   * @member {module:model/Lagerort} Lagerort
   */
  exports.prototype['Lagerort'] = undefined;
  /**
   * @member {module:model/Lagerplatz} Lagerplatz
   */
  exports.prototype['Lagerplatz'] = undefined;
  /**
   * @member {module:model/LagerortNach} LagerortNach
   */
  exports.prototype['LagerortNach'] = undefined;
  /**
   * @member {module:model/LagerplatzNach} LagerplatzNach
   */
  exports.prototype['LagerplatzNach'] = undefined;



  return exports;
}));


