/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Heimatland', 'model/Krankentaggeldversicherungscode1', 'model/Mitarbeiter', 'model/Unfallversicherungscode', 'model/Unfallzusatzversicherungscode1', 'model/Zahlungsart', 'model/Zivilstand'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Heimatland'), require('./Krankentaggeldversicherungscode1'), require('./Mitarbeiter'), require('./Unfallversicherungscode'), require('./Unfallzusatzversicherungscode1'), require('./Zahlungsart'), require('./Zivilstand'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.LOHMitarbeiterMitarbeiterNr = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Heimatland, root.ProffixRestApiRequestSammlung.Krankentaggeldversicherungscode1, root.ProffixRestApiRequestSammlung.Mitarbeiter, root.ProffixRestApiRequestSammlung.Unfallversicherungscode, root.ProffixRestApiRequestSammlung.Unfallzusatzversicherungscode1, root.ProffixRestApiRequestSammlung.Zahlungsart, root.ProffixRestApiRequestSammlung.Zivilstand);
  }
}(this, function(ApiClient, Heimatland, Krankentaggeldversicherungscode1, Mitarbeiter, Unfallversicherungscode, Unfallzusatzversicherungscode1, Zahlungsart, Zivilstand) {
  'use strict';




  /**
   * The LOHMitarbeiterMitarbeiterNr model module.
   * @module model/LOHMitarbeiterMitarbeiterNr
   * @version 1.0
   */

  /**
   * Constructs a new <code>LOHMitarbeiterMitarbeiterNr</code>.
   * @alias module:model/LOHMitarbeiterMitarbeiterNr
   * @class
   * @param mitarbeiterNr {Number} 
   * @param mitarbeiter {module:model/Mitarbeiter} 
   * @param geschlecht {String} 
   * @param heimatland {module:model/Heimatland} 
   * @param sozialversicherungsnummer {String} 
   * @param sozialversicherungsnummerFL {String} 
   * @param auftrag {String} 
   * @param kostenstelle {String} 
   * @param kostenart {String} 
   * @param habenkonto {String} 
   * @param sollkonto {String} 
   * @param bemerkungen {String} 
   * @param bemerkungenLohnausweis {String} 
   * @param zivilstand {module:model/Zivilstand} 
   * @param zahlungsart {module:model/Zahlungsart} 
   * @param heimatort {String} 
   * @param beruf {String} 
   * @param geloescht {Boolean} 
   * @param abteilung {String} 
   * @param aufenthaltskategorie {Number} 
   * @param arbeitsort {String} 
   * @param stundenlohn {Boolean} 
   * @param monatslohn {Boolean} 
   * @param beschaeftigungsgrad {Number} 
   * @param saisonnier {Boolean} 
   * @param zivilstandsdatum {String} 
   * @param krankentaggeldversicherungscode1 {module:model/Krankentaggeldversicherungscode1} 
   * @param krankentaggeldversicherungscode2 {String} 
   * @param unfallversicherungscode {module:model/Unfallversicherungscode} 
   * @param unfallzusatzversicherungscode1 {module:model/Unfallzusatzversicherungscode1} 
   * @param unfallzusatzversicherungscode2 {String} 
   * @param erstelltAm {String} 
   * @param erstelltVon {String} 
   * @param geaendertAm {String} 
   * @param geaendertVon {String} 
   */
  var exports = function(mitarbeiterNr, mitarbeiter, geschlecht, heimatland, sozialversicherungsnummer, sozialversicherungsnummerFL, auftrag, kostenstelle, kostenart, habenkonto, sollkonto, bemerkungen, bemerkungenLohnausweis, zivilstand, zahlungsart, heimatort, beruf, geloescht, abteilung, aufenthaltskategorie, arbeitsort, stundenlohn, monatslohn, beschaeftigungsgrad, saisonnier, zivilstandsdatum, krankentaggeldversicherungscode1, krankentaggeldversicherungscode2, unfallversicherungscode, unfallzusatzversicherungscode1, unfallzusatzversicherungscode2, erstelltAm, erstelltVon, geaendertAm, geaendertVon) {
    var _this = this;

    _this['MitarbeiterNr'] = mitarbeiterNr;
    _this['Mitarbeiter'] = mitarbeiter;
    _this['Geschlecht'] = geschlecht;
    _this['Heimatland'] = heimatland;
    _this['Sozialversicherungsnummer'] = sozialversicherungsnummer;
    _this['SozialversicherungsnummerFL'] = sozialversicherungsnummerFL;
    _this['Auftrag'] = auftrag;
    _this['Kostenstelle'] = kostenstelle;
    _this['Kostenart'] = kostenart;
    _this['Habenkonto'] = habenkonto;
    _this['Sollkonto'] = sollkonto;
    _this['Bemerkungen'] = bemerkungen;
    _this['BemerkungenLohnausweis'] = bemerkungenLohnausweis;
    _this['Zivilstand'] = zivilstand;
    _this['Zahlungsart'] = zahlungsart;
    _this['Heimatort'] = heimatort;
    _this['Beruf'] = beruf;
    _this['Geloescht'] = geloescht;
    _this['Abteilung'] = abteilung;
    _this['Aufenthaltskategorie'] = aufenthaltskategorie;
    _this['Arbeitsort'] = arbeitsort;
    _this['Stundenlohn'] = stundenlohn;
    _this['Monatslohn'] = monatslohn;
    _this['Beschaeftigungsgrad'] = beschaeftigungsgrad;
    _this['Saisonnier'] = saisonnier;
    _this['Zivilstandsdatum'] = zivilstandsdatum;
    _this['Krankentaggeldversicherungscode1'] = krankentaggeldversicherungscode1;
    _this['Krankentaggeldversicherungscode2'] = krankentaggeldversicherungscode2;
    _this['Unfallversicherungscode'] = unfallversicherungscode;
    _this['Unfallzusatzversicherungscode1'] = unfallzusatzversicherungscode1;
    _this['Unfallzusatzversicherungscode2'] = unfallzusatzversicherungscode2;
    _this['ErstelltAm'] = erstelltAm;
    _this['ErstelltVon'] = erstelltVon;
    _this['GeaendertAm'] = geaendertAm;
    _this['GeaendertVon'] = geaendertVon;
  };

  /**
   * Constructs a <code>LOHMitarbeiterMitarbeiterNr</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LOHMitarbeiterMitarbeiterNr} obj Optional instance to populate.
   * @return {module:model/LOHMitarbeiterMitarbeiterNr} The populated <code>LOHMitarbeiterMitarbeiterNr</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('MitarbeiterNr')) {
        obj['MitarbeiterNr'] = ApiClient.convertToType(data['MitarbeiterNr'], 'Number');
      }
      if (data.hasOwnProperty('Mitarbeiter')) {
        obj['Mitarbeiter'] = Mitarbeiter.constructFromObject(data['Mitarbeiter']);
      }
      if (data.hasOwnProperty('Geschlecht')) {
        obj['Geschlecht'] = ApiClient.convertToType(data['Geschlecht'], 'String');
      }
      if (data.hasOwnProperty('Heimatland')) {
        obj['Heimatland'] = Heimatland.constructFromObject(data['Heimatland']);
      }
      if (data.hasOwnProperty('Sozialversicherungsnummer')) {
        obj['Sozialversicherungsnummer'] = ApiClient.convertToType(data['Sozialversicherungsnummer'], 'String');
      }
      if (data.hasOwnProperty('SozialversicherungsnummerFL')) {
        obj['SozialversicherungsnummerFL'] = ApiClient.convertToType(data['SozialversicherungsnummerFL'], 'String');
      }
      if (data.hasOwnProperty('Auftrag')) {
        obj['Auftrag'] = ApiClient.convertToType(data['Auftrag'], 'String');
      }
      if (data.hasOwnProperty('Kostenstelle')) {
        obj['Kostenstelle'] = ApiClient.convertToType(data['Kostenstelle'], 'String');
      }
      if (data.hasOwnProperty('Kostenart')) {
        obj['Kostenart'] = ApiClient.convertToType(data['Kostenart'], 'String');
      }
      if (data.hasOwnProperty('Habenkonto')) {
        obj['Habenkonto'] = ApiClient.convertToType(data['Habenkonto'], 'String');
      }
      if (data.hasOwnProperty('Sollkonto')) {
        obj['Sollkonto'] = ApiClient.convertToType(data['Sollkonto'], 'String');
      }
      if (data.hasOwnProperty('Bemerkungen')) {
        obj['Bemerkungen'] = ApiClient.convertToType(data['Bemerkungen'], 'String');
      }
      if (data.hasOwnProperty('BemerkungenLohnausweis')) {
        obj['BemerkungenLohnausweis'] = ApiClient.convertToType(data['BemerkungenLohnausweis'], 'String');
      }
      if (data.hasOwnProperty('Zivilstand')) {
        obj['Zivilstand'] = Zivilstand.constructFromObject(data['Zivilstand']);
      }
      if (data.hasOwnProperty('Zahlungsart')) {
        obj['Zahlungsart'] = Zahlungsart.constructFromObject(data['Zahlungsart']);
      }
      if (data.hasOwnProperty('Heimatort')) {
        obj['Heimatort'] = ApiClient.convertToType(data['Heimatort'], 'String');
      }
      if (data.hasOwnProperty('Beruf')) {
        obj['Beruf'] = ApiClient.convertToType(data['Beruf'], 'String');
      }
      if (data.hasOwnProperty('Geloescht')) {
        obj['Geloescht'] = ApiClient.convertToType(data['Geloescht'], 'Boolean');
      }
      if (data.hasOwnProperty('Abteilung')) {
        obj['Abteilung'] = ApiClient.convertToType(data['Abteilung'], 'String');
      }
      if (data.hasOwnProperty('Aufenthaltskategorie')) {
        obj['Aufenthaltskategorie'] = ApiClient.convertToType(data['Aufenthaltskategorie'], 'Number');
      }
      if (data.hasOwnProperty('Arbeitsort')) {
        obj['Arbeitsort'] = ApiClient.convertToType(data['Arbeitsort'], 'String');
      }
      if (data.hasOwnProperty('Stundenlohn')) {
        obj['Stundenlohn'] = ApiClient.convertToType(data['Stundenlohn'], 'Boolean');
      }
      if (data.hasOwnProperty('Monatslohn')) {
        obj['Monatslohn'] = ApiClient.convertToType(data['Monatslohn'], 'Boolean');
      }
      if (data.hasOwnProperty('Beschaeftigungsgrad')) {
        obj['Beschaeftigungsgrad'] = ApiClient.convertToType(data['Beschaeftigungsgrad'], 'Number');
      }
      if (data.hasOwnProperty('Saisonnier')) {
        obj['Saisonnier'] = ApiClient.convertToType(data['Saisonnier'], 'Boolean');
      }
      if (data.hasOwnProperty('Zivilstandsdatum')) {
        obj['Zivilstandsdatum'] = ApiClient.convertToType(data['Zivilstandsdatum'], 'String');
      }
      if (data.hasOwnProperty('Krankentaggeldversicherungscode1')) {
        obj['Krankentaggeldversicherungscode1'] = Krankentaggeldversicherungscode1.constructFromObject(data['Krankentaggeldversicherungscode1']);
      }
      if (data.hasOwnProperty('Krankentaggeldversicherungscode2')) {
        obj['Krankentaggeldversicherungscode2'] = ApiClient.convertToType(data['Krankentaggeldversicherungscode2'], 'String');
      }
      if (data.hasOwnProperty('Unfallversicherungscode')) {
        obj['Unfallversicherungscode'] = Unfallversicherungscode.constructFromObject(data['Unfallversicherungscode']);
      }
      if (data.hasOwnProperty('Unfallzusatzversicherungscode1')) {
        obj['Unfallzusatzversicherungscode1'] = Unfallzusatzversicherungscode1.constructFromObject(data['Unfallzusatzversicherungscode1']);
      }
      if (data.hasOwnProperty('Unfallzusatzversicherungscode2')) {
        obj['Unfallzusatzversicherungscode2'] = ApiClient.convertToType(data['Unfallzusatzversicherungscode2'], 'String');
      }
      if (data.hasOwnProperty('ErstelltAm')) {
        obj['ErstelltAm'] = ApiClient.convertToType(data['ErstelltAm'], 'String');
      }
      if (data.hasOwnProperty('ErstelltVon')) {
        obj['ErstelltVon'] = ApiClient.convertToType(data['ErstelltVon'], 'String');
      }
      if (data.hasOwnProperty('GeaendertAm')) {
        obj['GeaendertAm'] = ApiClient.convertToType(data['GeaendertAm'], 'String');
      }
      if (data.hasOwnProperty('GeaendertVon')) {
        obj['GeaendertVon'] = ApiClient.convertToType(data['GeaendertVon'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} MitarbeiterNr
   */
  exports.prototype['MitarbeiterNr'] = undefined;
  /**
   * @member {module:model/Mitarbeiter} Mitarbeiter
   */
  exports.prototype['Mitarbeiter'] = undefined;
  /**
   * @member {String} Geschlecht
   */
  exports.prototype['Geschlecht'] = undefined;
  /**
   * @member {module:model/Heimatland} Heimatland
   */
  exports.prototype['Heimatland'] = undefined;
  /**
   * @member {String} Sozialversicherungsnummer
   */
  exports.prototype['Sozialversicherungsnummer'] = undefined;
  /**
   * @member {String} SozialversicherungsnummerFL
   */
  exports.prototype['SozialversicherungsnummerFL'] = undefined;
  /**
   * @member {String} Auftrag
   */
  exports.prototype['Auftrag'] = undefined;
  /**
   * @member {String} Kostenstelle
   */
  exports.prototype['Kostenstelle'] = undefined;
  /**
   * @member {String} Kostenart
   */
  exports.prototype['Kostenart'] = undefined;
  /**
   * @member {String} Habenkonto
   */
  exports.prototype['Habenkonto'] = undefined;
  /**
   * @member {String} Sollkonto
   */
  exports.prototype['Sollkonto'] = undefined;
  /**
   * @member {String} Bemerkungen
   */
  exports.prototype['Bemerkungen'] = undefined;
  /**
   * @member {String} BemerkungenLohnausweis
   */
  exports.prototype['BemerkungenLohnausweis'] = undefined;
  /**
   * @member {module:model/Zivilstand} Zivilstand
   */
  exports.prototype['Zivilstand'] = undefined;
  /**
   * @member {module:model/Zahlungsart} Zahlungsart
   */
  exports.prototype['Zahlungsart'] = undefined;
  /**
   * @member {String} Heimatort
   */
  exports.prototype['Heimatort'] = undefined;
  /**
   * @member {String} Beruf
   */
  exports.prototype['Beruf'] = undefined;
  /**
   * @member {Boolean} Geloescht
   */
  exports.prototype['Geloescht'] = undefined;
  /**
   * @member {String} Abteilung
   */
  exports.prototype['Abteilung'] = undefined;
  /**
   * @member {Number} Aufenthaltskategorie
   */
  exports.prototype['Aufenthaltskategorie'] = undefined;
  /**
   * @member {String} Arbeitsort
   */
  exports.prototype['Arbeitsort'] = undefined;
  /**
   * @member {Boolean} Stundenlohn
   */
  exports.prototype['Stundenlohn'] = undefined;
  /**
   * @member {Boolean} Monatslohn
   */
  exports.prototype['Monatslohn'] = undefined;
  /**
   * @member {Number} Beschaeftigungsgrad
   */
  exports.prototype['Beschaeftigungsgrad'] = undefined;
  /**
   * @member {Boolean} Saisonnier
   */
  exports.prototype['Saisonnier'] = undefined;
  /**
   * @member {String} Zivilstandsdatum
   */
  exports.prototype['Zivilstandsdatum'] = undefined;
  /**
   * @member {module:model/Krankentaggeldversicherungscode1} Krankentaggeldversicherungscode1
   */
  exports.prototype['Krankentaggeldversicherungscode1'] = undefined;
  /**
   * @member {String} Krankentaggeldversicherungscode2
   */
  exports.prototype['Krankentaggeldversicherungscode2'] = undefined;
  /**
   * @member {module:model/Unfallversicherungscode} Unfallversicherungscode
   */
  exports.prototype['Unfallversicherungscode'] = undefined;
  /**
   * @member {module:model/Unfallzusatzversicherungscode1} Unfallzusatzversicherungscode1
   */
  exports.prototype['Unfallzusatzversicherungscode1'] = undefined;
  /**
   * @member {String} Unfallzusatzversicherungscode2
   */
  exports.prototype['Unfallzusatzversicherungscode2'] = undefined;
  /**
   * @member {String} ErstelltAm
   */
  exports.prototype['ErstelltAm'] = undefined;
  /**
   * @member {String} ErstelltVon
   */
  exports.prototype['ErstelltVon'] = undefined;
  /**
   * @member {String} GeaendertAm
   */
  exports.prototype['GeaendertAm'] = undefined;
  /**
   * @member {String} GeaendertVon
   */
  exports.prototype['GeaendertVon'] = undefined;



  return exports;
}));


