/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Ertragskonto2', 'model/Steuercode1'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Ertragskonto2'), require('./Steuercode1'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.Positionen5 = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Ertragskonto2, root.ProffixRestApiRequestSammlung.Steuercode1);
  }
}(this, function(ApiClient, Ertragskonto2, Steuercode1) {
  'use strict';




  /**
   * The Positionen5 model module.
   * @module model/Positionen5
   * @version 1.0
   */

  /**
   * Constructs a new <code>Positionen5</code>.
   * @alias module:model/Positionen5
   * @class
   * @param positionNr {Number} 
   * @param artikel {String} 
   * @param auftrag {String} 
   * @param serviceauftrag {String} 
   * @param bezeichnung1 {String} 
   * @param bezeichnung2 {String} 
   * @param bezeichnung3 {String} 
   * @param bezeichnung4 {String} 
   * @param bezeichnung5 {String} 
   * @param bild {String} 
   * @param dim2 {Number} 
   * @param lagerbewegungen {String} 
   * @param eingangsstempel {String} 
   * @param lagereinheit {String} 
   * @param rechnungseinheit {String} 
   * @param einkaufspreisFW {Number} 
   * @param einkaufspreisSW {Number} 
   * @param ertragskonto {module:model/Ertragskonto2} 
   * @param gebinde {Number} 
   * @param gewicht {Number} 
   * @param gtinStufe {String} 
   * @param gutschein {String} 
   * @param inhalt {Number} 
   * @param istOption {Boolean} 
   * @param kundenbestellnummer {String} 
   * @param kundenbestellposition {String} 
   * @param kostenart {String} 
   * @param kostenstelle {String} 
   * @param dim1 {Number} 
   * @param lagerpreis {Number} 
   * @param lieferant {String} 
   * @param liefertermin {String} 
   * @param marge {Number} 
   * @param menge {Number} 
   * @param mengeOptional {Number} 
   * @param mengeVerr {Number} 
   * @param mengeVerrOptional {Number} 
   * @param occasionsObjektVerkauf {String} 
   * @param occasionsObjektAnkauf {String} 
   * @param occasionsObjektSerienummer {String} 
   * @param nichtAnzeigen {Boolean} 
   * @param externeNotizen {String} 
   * @param externeNotizenRTF {String} 
   * @param interneNotizen {String} 
   * @param interneNotizenRTF {String} 
   * @param optional {Boolean} 
   * @param positionsart {String} 
   * @param kundeninstallationen {Array.<String>} 
   * @param serviceauftragspositionNr {Number} 
   * @param positionstyp {Number} 
   * @param preisdefinition {String} 
   * @param preisdefinitionOptional {String} 
   * @param preisdefinitionZusatzartikel {String} 
   * @param preisFW {Number} 
   * @param preisSW {Number} 
   * @param rabattSW {Number} 
   * @param rabattFW {Number} 
   * @param rapport {String} 
   * @param automatischRechnenVon {Number} 
   * @param rekapitulation {Boolean} 
   * @param rueckstandMenge {Number} 
   * @param steuercode {module:model/Steuercode1} 
   * @param leistungsverwaltungstyp {Number} 
   * @param steuerFW {Number} 
   * @param steuerSW {Number} 
   * @param stuecklistenkopf {String} 
   * @param subtotalbezeichnungen {Array.<String>} 
   * @param dim3 {Number} 
   * @param totalFW {Number} 
   * @param totalInklusivFW {Number} 
   * @param totalInklusivSW {Number} 
   * @param totalOptional {Number} 
   * @param totalSW {Number} 
   * @param verpackungen {Number} 
   * @param vertreter {String} 
   * @param zusatzartikelreferenz {Number} 
   * @param rechnen {Boolean} 
   * @param gesamtrabattVerbuchungAufteilen {Boolean} 
   * @param erstelltAm {String} 
   * @param erstelltVon {String} 
   * @param geaendertAm {String} 
   * @param geaendertVon {String} 
   * @param zusatzfelder {Object} 
   */
  var exports = function(positionNr, artikel, auftrag, serviceauftrag, bezeichnung1, bezeichnung2, bezeichnung3, bezeichnung4, bezeichnung5, bild, dim2, lagerbewegungen, eingangsstempel, lagereinheit, rechnungseinheit, einkaufspreisFW, einkaufspreisSW, ertragskonto, gebinde, gewicht, gtinStufe, gutschein, inhalt, istOption, kundenbestellnummer, kundenbestellposition, kostenart, kostenstelle, dim1, lagerpreis, lieferant, liefertermin, marge, menge, mengeOptional, mengeVerr, mengeVerrOptional, occasionsObjektVerkauf, occasionsObjektAnkauf, occasionsObjektSerienummer, nichtAnzeigen, externeNotizen, externeNotizenRTF, interneNotizen, interneNotizenRTF, optional, positionsart, kundeninstallationen, serviceauftragspositionNr, positionstyp, preisdefinition, preisdefinitionOptional, preisdefinitionZusatzartikel, preisFW, preisSW, rabattSW, rabattFW, rapport, automatischRechnenVon, rekapitulation, rueckstandMenge, steuercode, leistungsverwaltungstyp, steuerFW, steuerSW, stuecklistenkopf, subtotalbezeichnungen, dim3, totalFW, totalInklusivFW, totalInklusivSW, totalOptional, totalSW, verpackungen, vertreter, zusatzartikelreferenz, rechnen, gesamtrabattVerbuchungAufteilen, erstelltAm, erstelltVon, geaendertAm, geaendertVon, zusatzfelder) {
    var _this = this;

    _this['PositionNr'] = positionNr;
    _this['Artikel'] = artikel;
    _this['Auftrag'] = auftrag;
    _this['Serviceauftrag'] = serviceauftrag;
    _this['Bezeichnung1'] = bezeichnung1;
    _this['Bezeichnung2'] = bezeichnung2;
    _this['Bezeichnung3'] = bezeichnung3;
    _this['Bezeichnung4'] = bezeichnung4;
    _this['Bezeichnung5'] = bezeichnung5;
    _this['Bild'] = bild;
    _this['Dim2'] = dim2;
    _this['Lagerbewegungen'] = lagerbewegungen;
    _this['Eingangsstempel'] = eingangsstempel;
    _this['Lagereinheit'] = lagereinheit;
    _this['Rechnungseinheit'] = rechnungseinheit;
    _this['EinkaufspreisFW'] = einkaufspreisFW;
    _this['EinkaufspreisSW'] = einkaufspreisSW;
    _this['Ertragskonto'] = ertragskonto;
    _this['Gebinde'] = gebinde;
    _this['Gewicht'] = gewicht;
    _this['GtinStufe'] = gtinStufe;
    _this['Gutschein'] = gutschein;
    _this['Inhalt'] = inhalt;
    _this['IstOption'] = istOption;
    _this['Kundenbestellnummer'] = kundenbestellnummer;
    _this['Kundenbestellposition'] = kundenbestellposition;
    _this['Kostenart'] = kostenart;
    _this['Kostenstelle'] = kostenstelle;
    _this['Dim1'] = dim1;
    _this['Lagerpreis'] = lagerpreis;
    _this['Lieferant'] = lieferant;
    _this['Liefertermin'] = liefertermin;
    _this['Marge'] = marge;
    _this['Menge'] = menge;
    _this['MengeOptional'] = mengeOptional;
    _this['MengeVerr'] = mengeVerr;
    _this['MengeVerrOptional'] = mengeVerrOptional;
    _this['OccasionsObjektVerkauf'] = occasionsObjektVerkauf;
    _this['OccasionsObjektAnkauf'] = occasionsObjektAnkauf;
    _this['OccasionsObjektSerienummer'] = occasionsObjektSerienummer;
    _this['NichtAnzeigen'] = nichtAnzeigen;
    _this['ExterneNotizen'] = externeNotizen;
    _this['ExterneNotizenRTF'] = externeNotizenRTF;
    _this['InterneNotizen'] = interneNotizen;
    _this['InterneNotizenRTF'] = interneNotizenRTF;
    _this['Optional'] = optional;
    _this['Positionsart'] = positionsart;
    _this['Kundeninstallationen'] = kundeninstallationen;
    _this['ServiceauftragspositionNr'] = serviceauftragspositionNr;
    _this['Positionstyp'] = positionstyp;
    _this['Preisdefinition'] = preisdefinition;
    _this['PreisdefinitionOptional'] = preisdefinitionOptional;
    _this['PreisdefinitionZusatzartikel'] = preisdefinitionZusatzartikel;
    _this['PreisFW'] = preisFW;
    _this['PreisSW'] = preisSW;
    _this['RabattSW'] = rabattSW;
    _this['RabattFW'] = rabattFW;
    _this['Rapport'] = rapport;
    _this['AutomatischRechnenVon'] = automatischRechnenVon;
    _this['Rekapitulation'] = rekapitulation;
    _this['RueckstandMenge'] = rueckstandMenge;
    _this['Steuercode'] = steuercode;
    _this['Leistungsverwaltungstyp'] = leistungsverwaltungstyp;
    _this['SteuerFW'] = steuerFW;
    _this['SteuerSW'] = steuerSW;
    _this['Stuecklistenkopf'] = stuecklistenkopf;
    _this['Subtotalbezeichnungen'] = subtotalbezeichnungen;
    _this['Dim3'] = dim3;
    _this['TotalFW'] = totalFW;
    _this['TotalInklusivFW'] = totalInklusivFW;
    _this['TotalInklusivSW'] = totalInklusivSW;
    _this['TotalOptional'] = totalOptional;
    _this['TotalSW'] = totalSW;
    _this['Verpackungen'] = verpackungen;
    _this['Vertreter'] = vertreter;
    _this['Zusatzartikelreferenz'] = zusatzartikelreferenz;
    _this['Rechnen'] = rechnen;
    _this['GesamtrabattVerbuchungAufteilen'] = gesamtrabattVerbuchungAufteilen;
    _this['ErstelltAm'] = erstelltAm;
    _this['ErstelltVon'] = erstelltVon;
    _this['GeaendertAm'] = geaendertAm;
    _this['GeaendertVon'] = geaendertVon;
    _this['Zusatzfelder'] = zusatzfelder;
  };

  /**
   * Constructs a <code>Positionen5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Positionen5} obj Optional instance to populate.
   * @return {module:model/Positionen5} The populated <code>Positionen5</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('PositionNr')) {
        obj['PositionNr'] = ApiClient.convertToType(data['PositionNr'], 'Number');
      }
      if (data.hasOwnProperty('Artikel')) {
        obj['Artikel'] = ApiClient.convertToType(data['Artikel'], 'String');
      }
      if (data.hasOwnProperty('Auftrag')) {
        obj['Auftrag'] = ApiClient.convertToType(data['Auftrag'], 'String');
      }
      if (data.hasOwnProperty('Serviceauftrag')) {
        obj['Serviceauftrag'] = ApiClient.convertToType(data['Serviceauftrag'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung1')) {
        obj['Bezeichnung1'] = ApiClient.convertToType(data['Bezeichnung1'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung2')) {
        obj['Bezeichnung2'] = ApiClient.convertToType(data['Bezeichnung2'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung3')) {
        obj['Bezeichnung3'] = ApiClient.convertToType(data['Bezeichnung3'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung4')) {
        obj['Bezeichnung4'] = ApiClient.convertToType(data['Bezeichnung4'], 'String');
      }
      if (data.hasOwnProperty('Bezeichnung5')) {
        obj['Bezeichnung5'] = ApiClient.convertToType(data['Bezeichnung5'], 'String');
      }
      if (data.hasOwnProperty('Bild')) {
        obj['Bild'] = ApiClient.convertToType(data['Bild'], 'String');
      }
      if (data.hasOwnProperty('Dim2')) {
        obj['Dim2'] = ApiClient.convertToType(data['Dim2'], 'Number');
      }
      if (data.hasOwnProperty('Lagerbewegungen')) {
        obj['Lagerbewegungen'] = ApiClient.convertToType(data['Lagerbewegungen'], 'String');
      }
      if (data.hasOwnProperty('Eingangsstempel')) {
        obj['Eingangsstempel'] = ApiClient.convertToType(data['Eingangsstempel'], 'String');
      }
      if (data.hasOwnProperty('Lagereinheit')) {
        obj['Lagereinheit'] = ApiClient.convertToType(data['Lagereinheit'], 'String');
      }
      if (data.hasOwnProperty('Rechnungseinheit')) {
        obj['Rechnungseinheit'] = ApiClient.convertToType(data['Rechnungseinheit'], 'String');
      }
      if (data.hasOwnProperty('EinkaufspreisFW')) {
        obj['EinkaufspreisFW'] = ApiClient.convertToType(data['EinkaufspreisFW'], 'Number');
      }
      if (data.hasOwnProperty('EinkaufspreisSW')) {
        obj['EinkaufspreisSW'] = ApiClient.convertToType(data['EinkaufspreisSW'], 'Number');
      }
      if (data.hasOwnProperty('Ertragskonto')) {
        obj['Ertragskonto'] = Ertragskonto2.constructFromObject(data['Ertragskonto']);
      }
      if (data.hasOwnProperty('Gebinde')) {
        obj['Gebinde'] = ApiClient.convertToType(data['Gebinde'], 'Number');
      }
      if (data.hasOwnProperty('Gewicht')) {
        obj['Gewicht'] = ApiClient.convertToType(data['Gewicht'], 'Number');
      }
      if (data.hasOwnProperty('GtinStufe')) {
        obj['GtinStufe'] = ApiClient.convertToType(data['GtinStufe'], 'String');
      }
      if (data.hasOwnProperty('Gutschein')) {
        obj['Gutschein'] = ApiClient.convertToType(data['Gutschein'], 'String');
      }
      if (data.hasOwnProperty('Inhalt')) {
        obj['Inhalt'] = ApiClient.convertToType(data['Inhalt'], 'Number');
      }
      if (data.hasOwnProperty('IstOption')) {
        obj['IstOption'] = ApiClient.convertToType(data['IstOption'], 'Boolean');
      }
      if (data.hasOwnProperty('Kundenbestellnummer')) {
        obj['Kundenbestellnummer'] = ApiClient.convertToType(data['Kundenbestellnummer'], 'String');
      }
      if (data.hasOwnProperty('Kundenbestellposition')) {
        obj['Kundenbestellposition'] = ApiClient.convertToType(data['Kundenbestellposition'], 'String');
      }
      if (data.hasOwnProperty('Kostenart')) {
        obj['Kostenart'] = ApiClient.convertToType(data['Kostenart'], 'String');
      }
      if (data.hasOwnProperty('Kostenstelle')) {
        obj['Kostenstelle'] = ApiClient.convertToType(data['Kostenstelle'], 'String');
      }
      if (data.hasOwnProperty('Dim1')) {
        obj['Dim1'] = ApiClient.convertToType(data['Dim1'], 'Number');
      }
      if (data.hasOwnProperty('Lagerpreis')) {
        obj['Lagerpreis'] = ApiClient.convertToType(data['Lagerpreis'], 'Number');
      }
      if (data.hasOwnProperty('Lieferant')) {
        obj['Lieferant'] = ApiClient.convertToType(data['Lieferant'], 'String');
      }
      if (data.hasOwnProperty('Liefertermin')) {
        obj['Liefertermin'] = ApiClient.convertToType(data['Liefertermin'], 'String');
      }
      if (data.hasOwnProperty('Marge')) {
        obj['Marge'] = ApiClient.convertToType(data['Marge'], 'Number');
      }
      if (data.hasOwnProperty('Menge')) {
        obj['Menge'] = ApiClient.convertToType(data['Menge'], 'Number');
      }
      if (data.hasOwnProperty('MengeOptional')) {
        obj['MengeOptional'] = ApiClient.convertToType(data['MengeOptional'], 'Number');
      }
      if (data.hasOwnProperty('MengeVerr')) {
        obj['MengeVerr'] = ApiClient.convertToType(data['MengeVerr'], 'Number');
      }
      if (data.hasOwnProperty('MengeVerrOptional')) {
        obj['MengeVerrOptional'] = ApiClient.convertToType(data['MengeVerrOptional'], 'Number');
      }
      if (data.hasOwnProperty('OccasionsObjektVerkauf')) {
        obj['OccasionsObjektVerkauf'] = ApiClient.convertToType(data['OccasionsObjektVerkauf'], 'String');
      }
      if (data.hasOwnProperty('OccasionsObjektAnkauf')) {
        obj['OccasionsObjektAnkauf'] = ApiClient.convertToType(data['OccasionsObjektAnkauf'], 'String');
      }
      if (data.hasOwnProperty('OccasionsObjektSerienummer')) {
        obj['OccasionsObjektSerienummer'] = ApiClient.convertToType(data['OccasionsObjektSerienummer'], 'String');
      }
      if (data.hasOwnProperty('NichtAnzeigen')) {
        obj['NichtAnzeigen'] = ApiClient.convertToType(data['NichtAnzeigen'], 'Boolean');
      }
      if (data.hasOwnProperty('ExterneNotizen')) {
        obj['ExterneNotizen'] = ApiClient.convertToType(data['ExterneNotizen'], 'String');
      }
      if (data.hasOwnProperty('ExterneNotizenRTF')) {
        obj['ExterneNotizenRTF'] = ApiClient.convertToType(data['ExterneNotizenRTF'], 'String');
      }
      if (data.hasOwnProperty('InterneNotizen')) {
        obj['InterneNotizen'] = ApiClient.convertToType(data['InterneNotizen'], 'String');
      }
      if (data.hasOwnProperty('InterneNotizenRTF')) {
        obj['InterneNotizenRTF'] = ApiClient.convertToType(data['InterneNotizenRTF'], 'String');
      }
      if (data.hasOwnProperty('Optional')) {
        obj['Optional'] = ApiClient.convertToType(data['Optional'], 'Boolean');
      }
      if (data.hasOwnProperty('Positionsart')) {
        obj['Positionsart'] = ApiClient.convertToType(data['Positionsart'], 'String');
      }
      if (data.hasOwnProperty('Kundeninstallationen')) {
        obj['Kundeninstallationen'] = ApiClient.convertToType(data['Kundeninstallationen'], ['String']);
      }
      if (data.hasOwnProperty('ServiceauftragspositionNr')) {
        obj['ServiceauftragspositionNr'] = ApiClient.convertToType(data['ServiceauftragspositionNr'], 'Number');
      }
      if (data.hasOwnProperty('Positionstyp')) {
        obj['Positionstyp'] = ApiClient.convertToType(data['Positionstyp'], 'Number');
      }
      if (data.hasOwnProperty('Preisdefinition')) {
        obj['Preisdefinition'] = ApiClient.convertToType(data['Preisdefinition'], 'String');
      }
      if (data.hasOwnProperty('PreisdefinitionOptional')) {
        obj['PreisdefinitionOptional'] = ApiClient.convertToType(data['PreisdefinitionOptional'], 'String');
      }
      if (data.hasOwnProperty('PreisdefinitionZusatzartikel')) {
        obj['PreisdefinitionZusatzartikel'] = ApiClient.convertToType(data['PreisdefinitionZusatzartikel'], 'String');
      }
      if (data.hasOwnProperty('PreisFW')) {
        obj['PreisFW'] = ApiClient.convertToType(data['PreisFW'], 'Number');
      }
      if (data.hasOwnProperty('PreisSW')) {
        obj['PreisSW'] = ApiClient.convertToType(data['PreisSW'], 'Number');
      }
      if (data.hasOwnProperty('RabattSW')) {
        obj['RabattSW'] = ApiClient.convertToType(data['RabattSW'], 'Number');
      }
      if (data.hasOwnProperty('RabattFW')) {
        obj['RabattFW'] = ApiClient.convertToType(data['RabattFW'], 'Number');
      }
      if (data.hasOwnProperty('Rapport')) {
        obj['Rapport'] = ApiClient.convertToType(data['Rapport'], 'String');
      }
      if (data.hasOwnProperty('AutomatischRechnenVon')) {
        obj['AutomatischRechnenVon'] = ApiClient.convertToType(data['AutomatischRechnenVon'], 'Number');
      }
      if (data.hasOwnProperty('Rekapitulation')) {
        obj['Rekapitulation'] = ApiClient.convertToType(data['Rekapitulation'], 'Boolean');
      }
      if (data.hasOwnProperty('RueckstandMenge')) {
        obj['RueckstandMenge'] = ApiClient.convertToType(data['RueckstandMenge'], 'Number');
      }
      if (data.hasOwnProperty('Steuercode')) {
        obj['Steuercode'] = Steuercode1.constructFromObject(data['Steuercode']);
      }
      if (data.hasOwnProperty('Leistungsverwaltungstyp')) {
        obj['Leistungsverwaltungstyp'] = ApiClient.convertToType(data['Leistungsverwaltungstyp'], 'Number');
      }
      if (data.hasOwnProperty('SteuerFW')) {
        obj['SteuerFW'] = ApiClient.convertToType(data['SteuerFW'], 'Number');
      }
      if (data.hasOwnProperty('SteuerSW')) {
        obj['SteuerSW'] = ApiClient.convertToType(data['SteuerSW'], 'Number');
      }
      if (data.hasOwnProperty('Stuecklistenkopf')) {
        obj['Stuecklistenkopf'] = ApiClient.convertToType(data['Stuecklistenkopf'], 'String');
      }
      if (data.hasOwnProperty('Subtotalbezeichnungen')) {
        obj['Subtotalbezeichnungen'] = ApiClient.convertToType(data['Subtotalbezeichnungen'], ['String']);
      }
      if (data.hasOwnProperty('Dim3')) {
        obj['Dim3'] = ApiClient.convertToType(data['Dim3'], 'Number');
      }
      if (data.hasOwnProperty('TotalFW')) {
        obj['TotalFW'] = ApiClient.convertToType(data['TotalFW'], 'Number');
      }
      if (data.hasOwnProperty('TotalInklusivFW')) {
        obj['TotalInklusivFW'] = ApiClient.convertToType(data['TotalInklusivFW'], 'Number');
      }
      if (data.hasOwnProperty('TotalInklusivSW')) {
        obj['TotalInklusivSW'] = ApiClient.convertToType(data['TotalInklusivSW'], 'Number');
      }
      if (data.hasOwnProperty('TotalOptional')) {
        obj['TotalOptional'] = ApiClient.convertToType(data['TotalOptional'], 'Number');
      }
      if (data.hasOwnProperty('TotalSW')) {
        obj['TotalSW'] = ApiClient.convertToType(data['TotalSW'], 'Number');
      }
      if (data.hasOwnProperty('Verpackungen')) {
        obj['Verpackungen'] = ApiClient.convertToType(data['Verpackungen'], 'Number');
      }
      if (data.hasOwnProperty('Vertreter')) {
        obj['Vertreter'] = ApiClient.convertToType(data['Vertreter'], 'String');
      }
      if (data.hasOwnProperty('Zusatzartikelreferenz')) {
        obj['Zusatzartikelreferenz'] = ApiClient.convertToType(data['Zusatzartikelreferenz'], 'Number');
      }
      if (data.hasOwnProperty('Rechnen')) {
        obj['Rechnen'] = ApiClient.convertToType(data['Rechnen'], 'Boolean');
      }
      if (data.hasOwnProperty('GesamtrabattVerbuchungAufteilen')) {
        obj['GesamtrabattVerbuchungAufteilen'] = ApiClient.convertToType(data['GesamtrabattVerbuchungAufteilen'], 'Boolean');
      }
      if (data.hasOwnProperty('ErstelltAm')) {
        obj['ErstelltAm'] = ApiClient.convertToType(data['ErstelltAm'], 'String');
      }
      if (data.hasOwnProperty('ErstelltVon')) {
        obj['ErstelltVon'] = ApiClient.convertToType(data['ErstelltVon'], 'String');
      }
      if (data.hasOwnProperty('GeaendertAm')) {
        obj['GeaendertAm'] = ApiClient.convertToType(data['GeaendertAm'], 'String');
      }
      if (data.hasOwnProperty('GeaendertVon')) {
        obj['GeaendertVon'] = ApiClient.convertToType(data['GeaendertVon'], 'String');
      }
      if (data.hasOwnProperty('Zusatzfelder')) {
        obj['Zusatzfelder'] = ApiClient.convertToType(data['Zusatzfelder'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Number} PositionNr
   */
  exports.prototype['PositionNr'] = undefined;
  /**
   * @member {String} Artikel
   */
  exports.prototype['Artikel'] = undefined;
  /**
   * @member {String} Auftrag
   */
  exports.prototype['Auftrag'] = undefined;
  /**
   * @member {String} Serviceauftrag
   */
  exports.prototype['Serviceauftrag'] = undefined;
  /**
   * @member {String} Bezeichnung1
   */
  exports.prototype['Bezeichnung1'] = undefined;
  /**
   * @member {String} Bezeichnung2
   */
  exports.prototype['Bezeichnung2'] = undefined;
  /**
   * @member {String} Bezeichnung3
   */
  exports.prototype['Bezeichnung3'] = undefined;
  /**
   * @member {String} Bezeichnung4
   */
  exports.prototype['Bezeichnung4'] = undefined;
  /**
   * @member {String} Bezeichnung5
   */
  exports.prototype['Bezeichnung5'] = undefined;
  /**
   * @member {String} Bild
   */
  exports.prototype['Bild'] = undefined;
  /**
   * @member {Number} Dim2
   */
  exports.prototype['Dim2'] = undefined;
  /**
   * @member {String} Lagerbewegungen
   */
  exports.prototype['Lagerbewegungen'] = undefined;
  /**
   * @member {String} Eingangsstempel
   */
  exports.prototype['Eingangsstempel'] = undefined;
  /**
   * @member {String} Lagereinheit
   */
  exports.prototype['Lagereinheit'] = undefined;
  /**
   * @member {String} Rechnungseinheit
   */
  exports.prototype['Rechnungseinheit'] = undefined;
  /**
   * @member {Number} EinkaufspreisFW
   */
  exports.prototype['EinkaufspreisFW'] = undefined;
  /**
   * @member {Number} EinkaufspreisSW
   */
  exports.prototype['EinkaufspreisSW'] = undefined;
  /**
   * @member {module:model/Ertragskonto2} Ertragskonto
   */
  exports.prototype['Ertragskonto'] = undefined;
  /**
   * @member {Number} Gebinde
   */
  exports.prototype['Gebinde'] = undefined;
  /**
   * @member {Number} Gewicht
   */
  exports.prototype['Gewicht'] = undefined;
  /**
   * @member {String} GtinStufe
   */
  exports.prototype['GtinStufe'] = undefined;
  /**
   * @member {String} Gutschein
   */
  exports.prototype['Gutschein'] = undefined;
  /**
   * @member {Number} Inhalt
   */
  exports.prototype['Inhalt'] = undefined;
  /**
   * @member {Boolean} IstOption
   */
  exports.prototype['IstOption'] = undefined;
  /**
   * @member {String} Kundenbestellnummer
   */
  exports.prototype['Kundenbestellnummer'] = undefined;
  /**
   * @member {String} Kundenbestellposition
   */
  exports.prototype['Kundenbestellposition'] = undefined;
  /**
   * @member {String} Kostenart
   */
  exports.prototype['Kostenart'] = undefined;
  /**
   * @member {String} Kostenstelle
   */
  exports.prototype['Kostenstelle'] = undefined;
  /**
   * @member {Number} Dim1
   */
  exports.prototype['Dim1'] = undefined;
  /**
   * @member {Number} Lagerpreis
   */
  exports.prototype['Lagerpreis'] = undefined;
  /**
   * @member {String} Lieferant
   */
  exports.prototype['Lieferant'] = undefined;
  /**
   * @member {String} Liefertermin
   */
  exports.prototype['Liefertermin'] = undefined;
  /**
   * @member {Number} Marge
   */
  exports.prototype['Marge'] = undefined;
  /**
   * @member {Number} Menge
   */
  exports.prototype['Menge'] = undefined;
  /**
   * @member {Number} MengeOptional
   */
  exports.prototype['MengeOptional'] = undefined;
  /**
   * @member {Number} MengeVerr
   */
  exports.prototype['MengeVerr'] = undefined;
  /**
   * @member {Number} MengeVerrOptional
   */
  exports.prototype['MengeVerrOptional'] = undefined;
  /**
   * @member {String} OccasionsObjektVerkauf
   */
  exports.prototype['OccasionsObjektVerkauf'] = undefined;
  /**
   * @member {String} OccasionsObjektAnkauf
   */
  exports.prototype['OccasionsObjektAnkauf'] = undefined;
  /**
   * @member {String} OccasionsObjektSerienummer
   */
  exports.prototype['OccasionsObjektSerienummer'] = undefined;
  /**
   * @member {Boolean} NichtAnzeigen
   */
  exports.prototype['NichtAnzeigen'] = undefined;
  /**
   * @member {String} ExterneNotizen
   */
  exports.prototype['ExterneNotizen'] = undefined;
  /**
   * @member {String} ExterneNotizenRTF
   */
  exports.prototype['ExterneNotizenRTF'] = undefined;
  /**
   * @member {String} InterneNotizen
   */
  exports.prototype['InterneNotizen'] = undefined;
  /**
   * @member {String} InterneNotizenRTF
   */
  exports.prototype['InterneNotizenRTF'] = undefined;
  /**
   * @member {Boolean} Optional
   */
  exports.prototype['Optional'] = undefined;
  /**
   * @member {String} Positionsart
   */
  exports.prototype['Positionsart'] = undefined;
  /**
   * @member {Array.<String>} Kundeninstallationen
   */
  exports.prototype['Kundeninstallationen'] = undefined;
  /**
   * @member {Number} ServiceauftragspositionNr
   */
  exports.prototype['ServiceauftragspositionNr'] = undefined;
  /**
   * @member {Number} Positionstyp
   */
  exports.prototype['Positionstyp'] = undefined;
  /**
   * @member {String} Preisdefinition
   */
  exports.prototype['Preisdefinition'] = undefined;
  /**
   * @member {String} PreisdefinitionOptional
   */
  exports.prototype['PreisdefinitionOptional'] = undefined;
  /**
   * @member {String} PreisdefinitionZusatzartikel
   */
  exports.prototype['PreisdefinitionZusatzartikel'] = undefined;
  /**
   * @member {Number} PreisFW
   */
  exports.prototype['PreisFW'] = undefined;
  /**
   * @member {Number} PreisSW
   */
  exports.prototype['PreisSW'] = undefined;
  /**
   * @member {Number} RabattSW
   */
  exports.prototype['RabattSW'] = undefined;
  /**
   * @member {Number} RabattFW
   */
  exports.prototype['RabattFW'] = undefined;
  /**
   * @member {String} Rapport
   */
  exports.prototype['Rapport'] = undefined;
  /**
   * @member {Number} AutomatischRechnenVon
   */
  exports.prototype['AutomatischRechnenVon'] = undefined;
  /**
   * @member {Boolean} Rekapitulation
   */
  exports.prototype['Rekapitulation'] = undefined;
  /**
   * @member {Number} RueckstandMenge
   */
  exports.prototype['RueckstandMenge'] = undefined;
  /**
   * @member {module:model/Steuercode1} Steuercode
   */
  exports.prototype['Steuercode'] = undefined;
  /**
   * @member {Number} Leistungsverwaltungstyp
   */
  exports.prototype['Leistungsverwaltungstyp'] = undefined;
  /**
   * @member {Number} SteuerFW
   */
  exports.prototype['SteuerFW'] = undefined;
  /**
   * @member {Number} SteuerSW
   */
  exports.prototype['SteuerSW'] = undefined;
  /**
   * @member {String} Stuecklistenkopf
   */
  exports.prototype['Stuecklistenkopf'] = undefined;
  /**
   * @member {Array.<String>} Subtotalbezeichnungen
   */
  exports.prototype['Subtotalbezeichnungen'] = undefined;
  /**
   * @member {Number} Dim3
   */
  exports.prototype['Dim3'] = undefined;
  /**
   * @member {Number} TotalFW
   */
  exports.prototype['TotalFW'] = undefined;
  /**
   * @member {Number} TotalInklusivFW
   */
  exports.prototype['TotalInklusivFW'] = undefined;
  /**
   * @member {Number} TotalInklusivSW
   */
  exports.prototype['TotalInklusivSW'] = undefined;
  /**
   * @member {Number} TotalOptional
   */
  exports.prototype['TotalOptional'] = undefined;
  /**
   * @member {Number} TotalSW
   */
  exports.prototype['TotalSW'] = undefined;
  /**
   * @member {Number} Verpackungen
   */
  exports.prototype['Verpackungen'] = undefined;
  /**
   * @member {String} Vertreter
   */
  exports.prototype['Vertreter'] = undefined;
  /**
   * @member {Number} Zusatzartikelreferenz
   */
  exports.prototype['Zusatzartikelreferenz'] = undefined;
  /**
   * @member {Boolean} Rechnen
   */
  exports.prototype['Rechnen'] = undefined;
  /**
   * @member {Boolean} GesamtrabattVerbuchungAufteilen
   */
  exports.prototype['GesamtrabattVerbuchungAufteilen'] = undefined;
  /**
   * @member {String} ErstelltAm
   */
  exports.prototype['ErstelltAm'] = undefined;
  /**
   * @member {String} ErstelltVon
   */
  exports.prototype['ErstelltVon'] = undefined;
  /**
   * @member {String} GeaendertAm
   */
  exports.prototype['GeaendertAm'] = undefined;
  /**
   * @member {String} GeaendertVon
   */
  exports.prototype['GeaendertVon'] = undefined;
  /**
   * @member {Object} Zusatzfelder
   */
  exports.prototype['Zusatzfelder'] = undefined;



  return exports;
}));


