/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Adresse', 'model/Stundenart', 'model/Zusatzfelder10'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Adresse'), require('./Stundenart'), require('./Zusatzfelder10'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.PROMitarbeiterMitarbeiterNr = factory(root.ProffixRestApiRequestSammlung.ApiClient, root.ProffixRestApiRequestSammlung.Adresse, root.ProffixRestApiRequestSammlung.Stundenart, root.ProffixRestApiRequestSammlung.Zusatzfelder10);
  }
}(this, function(ApiClient, Adresse, Stundenart, Zusatzfelder10) {
  'use strict';




  /**
   * The PROMitarbeiterMitarbeiterNr model module.
   * @module model/PROMitarbeiterMitarbeiterNr
   * @version 1.0
   */

  /**
   * Constructs a new <code>PROMitarbeiterMitarbeiterNr</code>.
   * @alias module:model/PROMitarbeiterMitarbeiterNr
   * @class
   * @param mitarbeiterNr {Number} 
   * @param name {String} 
   * @param kurzzeichen {String} 
   * @param adresse {module:model/Adresse} 
   * @param positionsart {String} 
   * @param stundenart {module:model/Stundenart} 
   * @param feriensaldo {Number} 
   * @param badgeID {String} 
   * @param geloescht {Boolean} 
   * @param benutzergruppe {String} 
   * @param bemerkungen {String} 
   * @param bemerkungenLeistungsverwaltung {String} 
   * @param bemerkungenZeitverwaltung {String} 
   * @param austrittsdatum {String} 
   * @param eintrittsdatum {String} 
   * @param funktion {String} 
   * @param erstelltAm {String} 
   * @param erstelltVon {String} 
   * @param geaendertAm {String} 
   * @param geaendertVon {String} 
   * @param zusatzfelder {module:model/Zusatzfelder10} 
   */
  var exports = function(mitarbeiterNr, name, kurzzeichen, adresse, positionsart, stundenart, feriensaldo, badgeID, geloescht, benutzergruppe, bemerkungen, bemerkungenLeistungsverwaltung, bemerkungenZeitverwaltung, austrittsdatum, eintrittsdatum, funktion, erstelltAm, erstelltVon, geaendertAm, geaendertVon, zusatzfelder) {
    var _this = this;

    _this['MitarbeiterNr'] = mitarbeiterNr;
    _this['Name'] = name;
    _this['Kurzzeichen'] = kurzzeichen;
    _this['Adresse'] = adresse;
    _this['Positionsart'] = positionsart;
    _this['Stundenart'] = stundenart;
    _this['Feriensaldo'] = feriensaldo;
    _this['BadgeID'] = badgeID;
    _this['Geloescht'] = geloescht;
    _this['Benutzergruppe'] = benutzergruppe;
    _this['Bemerkungen'] = bemerkungen;
    _this['BemerkungenLeistungsverwaltung'] = bemerkungenLeistungsverwaltung;
    _this['BemerkungenZeitverwaltung'] = bemerkungenZeitverwaltung;
    _this['Austrittsdatum'] = austrittsdatum;
    _this['Eintrittsdatum'] = eintrittsdatum;
    _this['Funktion'] = funktion;
    _this['ErstelltAm'] = erstelltAm;
    _this['ErstelltVon'] = erstelltVon;
    _this['GeaendertAm'] = geaendertAm;
    _this['GeaendertVon'] = geaendertVon;
    _this['Zusatzfelder'] = zusatzfelder;
  };

  /**
   * Constructs a <code>PROMitarbeiterMitarbeiterNr</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PROMitarbeiterMitarbeiterNr} obj Optional instance to populate.
   * @return {module:model/PROMitarbeiterMitarbeiterNr} The populated <code>PROMitarbeiterMitarbeiterNr</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('MitarbeiterNr')) {
        obj['MitarbeiterNr'] = ApiClient.convertToType(data['MitarbeiterNr'], 'Number');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Kurzzeichen')) {
        obj['Kurzzeichen'] = ApiClient.convertToType(data['Kurzzeichen'], 'String');
      }
      if (data.hasOwnProperty('Adresse')) {
        obj['Adresse'] = Adresse.constructFromObject(data['Adresse']);
      }
      if (data.hasOwnProperty('Positionsart')) {
        obj['Positionsart'] = ApiClient.convertToType(data['Positionsart'], 'String');
      }
      if (data.hasOwnProperty('Stundenart')) {
        obj['Stundenart'] = Stundenart.constructFromObject(data['Stundenart']);
      }
      if (data.hasOwnProperty('Feriensaldo')) {
        obj['Feriensaldo'] = ApiClient.convertToType(data['Feriensaldo'], 'Number');
      }
      if (data.hasOwnProperty('BadgeID')) {
        obj['BadgeID'] = ApiClient.convertToType(data['BadgeID'], 'String');
      }
      if (data.hasOwnProperty('Geloescht')) {
        obj['Geloescht'] = ApiClient.convertToType(data['Geloescht'], 'Boolean');
      }
      if (data.hasOwnProperty('Benutzergruppe')) {
        obj['Benutzergruppe'] = ApiClient.convertToType(data['Benutzergruppe'], 'String');
      }
      if (data.hasOwnProperty('Bemerkungen')) {
        obj['Bemerkungen'] = ApiClient.convertToType(data['Bemerkungen'], 'String');
      }
      if (data.hasOwnProperty('BemerkungenLeistungsverwaltung')) {
        obj['BemerkungenLeistungsverwaltung'] = ApiClient.convertToType(data['BemerkungenLeistungsverwaltung'], 'String');
      }
      if (data.hasOwnProperty('BemerkungenZeitverwaltung')) {
        obj['BemerkungenZeitverwaltung'] = ApiClient.convertToType(data['BemerkungenZeitverwaltung'], 'String');
      }
      if (data.hasOwnProperty('Austrittsdatum')) {
        obj['Austrittsdatum'] = ApiClient.convertToType(data['Austrittsdatum'], 'String');
      }
      if (data.hasOwnProperty('Eintrittsdatum')) {
        obj['Eintrittsdatum'] = ApiClient.convertToType(data['Eintrittsdatum'], 'String');
      }
      if (data.hasOwnProperty('Funktion')) {
        obj['Funktion'] = ApiClient.convertToType(data['Funktion'], 'String');
      }
      if (data.hasOwnProperty('ErstelltAm')) {
        obj['ErstelltAm'] = ApiClient.convertToType(data['ErstelltAm'], 'String');
      }
      if (data.hasOwnProperty('ErstelltVon')) {
        obj['ErstelltVon'] = ApiClient.convertToType(data['ErstelltVon'], 'String');
      }
      if (data.hasOwnProperty('GeaendertAm')) {
        obj['GeaendertAm'] = ApiClient.convertToType(data['GeaendertAm'], 'String');
      }
      if (data.hasOwnProperty('GeaendertVon')) {
        obj['GeaendertVon'] = ApiClient.convertToType(data['GeaendertVon'], 'String');
      }
      if (data.hasOwnProperty('Zusatzfelder')) {
        obj['Zusatzfelder'] = Zusatzfelder10.constructFromObject(data['Zusatzfelder']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} MitarbeiterNr
   */
  exports.prototype['MitarbeiterNr'] = undefined;
  /**
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * @member {String} Kurzzeichen
   */
  exports.prototype['Kurzzeichen'] = undefined;
  /**
   * @member {module:model/Adresse} Adresse
   */
  exports.prototype['Adresse'] = undefined;
  /**
   * @member {String} Positionsart
   */
  exports.prototype['Positionsart'] = undefined;
  /**
   * @member {module:model/Stundenart} Stundenart
   */
  exports.prototype['Stundenart'] = undefined;
  /**
   * @member {Number} Feriensaldo
   */
  exports.prototype['Feriensaldo'] = undefined;
  /**
   * @member {String} BadgeID
   */
  exports.prototype['BadgeID'] = undefined;
  /**
   * @member {Boolean} Geloescht
   */
  exports.prototype['Geloescht'] = undefined;
  /**
   * @member {String} Benutzergruppe
   */
  exports.prototype['Benutzergruppe'] = undefined;
  /**
   * @member {String} Bemerkungen
   */
  exports.prototype['Bemerkungen'] = undefined;
  /**
   * @member {String} BemerkungenLeistungsverwaltung
   */
  exports.prototype['BemerkungenLeistungsverwaltung'] = undefined;
  /**
   * @member {String} BemerkungenZeitverwaltung
   */
  exports.prototype['BemerkungenZeitverwaltung'] = undefined;
  /**
   * @member {String} Austrittsdatum
   */
  exports.prototype['Austrittsdatum'] = undefined;
  /**
   * @member {String} Eintrittsdatum
   */
  exports.prototype['Eintrittsdatum'] = undefined;
  /**
   * @member {String} Funktion
   */
  exports.prototype['Funktion'] = undefined;
  /**
   * @member {String} ErstelltAm
   */
  exports.prototype['ErstelltAm'] = undefined;
  /**
   * @member {String} ErstelltVon
   */
  exports.prototype['ErstelltVon'] = undefined;
  /**
   * @member {String} GeaendertAm
   */
  exports.prototype['GeaendertAm'] = undefined;
  /**
   * @member {String} GeaendertVon
   */
  exports.prototype['GeaendertVon'] = undefined;
  /**
   * @member {module:model/Zusatzfelder10} Zusatzfelder
   */
  exports.prototype['Zusatzfelder'] = undefined;



  return exports;
}));


