/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ProffixRestApiRequestSammlung) {
      root.ProffixRestApiRequestSammlung = {};
    }
    root.ProffixRestApiRequestSammlung.Zusatzfelder4 = factory(root.ProffixRestApiRequestSammlung.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Zusatzfelder4 model module.
   * @module model/Zusatzfelder4
   * @version 1.0
   */

  /**
   * Constructs a new <code>Zusatzfelder4</code>.
   * @alias module:model/Zusatzfelder4
   * @class
   * @param zAblaufdatum {String} 
   * @param zBehandlungsgrund {String} 
   * @param zBemerkungen {String} 
   * @param zBenhandlungbeginn {String} 
   * @param zBenhandlungende {String} 
   * @param zDiagnose {String} 
   * @param zEmpfNgerReferenz {String} 
   * @param zGesetz {String} 
   * @param zRolle {String} 
   * @param zStandort {String} 
   * @param zVersandart {String} 
   * @param zVersenderReferenz {String} 
   * @param zZuweiser {Number} 
   */
  var exports = function(zAblaufdatum, zBehandlungsgrund, zBemerkungen, zBenhandlungbeginn, zBenhandlungende, zDiagnose, zEmpfNgerReferenz, zGesetz, zRolle, zStandort, zVersandart, zVersenderReferenz, zZuweiser) {
    var _this = this;

    _this['Z_Ablaufdatum'] = zAblaufdatum;
    _this['Z_Behandlungsgrund'] = zBehandlungsgrund;
    _this['Z_Bemerkungen'] = zBemerkungen;
    _this['Z_Benhandlungbeginn'] = zBenhandlungbeginn;
    _this['Z_Benhandlungende'] = zBenhandlungende;
    _this['Z_Diagnose'] = zDiagnose;
    _this['Z_Empf_nger_Referenz'] = zEmpfNgerReferenz;
    _this['Z_Gesetz'] = zGesetz;
    _this['Z_Rolle'] = zRolle;
    _this['Z_Standort'] = zStandort;
    _this['Z_Versandart'] = zVersandart;
    _this['Z_Versender_Referenz'] = zVersenderReferenz;
    _this['Z_Zuweiser'] = zZuweiser;
  };

  /**
   * Constructs a <code>Zusatzfelder4</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Zusatzfelder4} obj Optional instance to populate.
   * @return {module:model/Zusatzfelder4} The populated <code>Zusatzfelder4</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Z_Ablaufdatum')) {
        obj['Z_Ablaufdatum'] = ApiClient.convertToType(data['Z_Ablaufdatum'], 'String');
      }
      if (data.hasOwnProperty('Z_Behandlungsgrund')) {
        obj['Z_Behandlungsgrund'] = ApiClient.convertToType(data['Z_Behandlungsgrund'], 'String');
      }
      if (data.hasOwnProperty('Z_Bemerkungen')) {
        obj['Z_Bemerkungen'] = ApiClient.convertToType(data['Z_Bemerkungen'], 'String');
      }
      if (data.hasOwnProperty('Z_Benhandlungbeginn')) {
        obj['Z_Benhandlungbeginn'] = ApiClient.convertToType(data['Z_Benhandlungbeginn'], 'String');
      }
      if (data.hasOwnProperty('Z_Benhandlungende')) {
        obj['Z_Benhandlungende'] = ApiClient.convertToType(data['Z_Benhandlungende'], 'String');
      }
      if (data.hasOwnProperty('Z_Diagnose')) {
        obj['Z_Diagnose'] = ApiClient.convertToType(data['Z_Diagnose'], 'String');
      }
      if (data.hasOwnProperty('Z_Empf_nger_Referenz')) {
        obj['Z_Empf_nger_Referenz'] = ApiClient.convertToType(data['Z_Empf_nger_Referenz'], 'String');
      }
      if (data.hasOwnProperty('Z_Gesetz')) {
        obj['Z_Gesetz'] = ApiClient.convertToType(data['Z_Gesetz'], 'String');
      }
      if (data.hasOwnProperty('Z_Rolle')) {
        obj['Z_Rolle'] = ApiClient.convertToType(data['Z_Rolle'], 'String');
      }
      if (data.hasOwnProperty('Z_Standort')) {
        obj['Z_Standort'] = ApiClient.convertToType(data['Z_Standort'], 'String');
      }
      if (data.hasOwnProperty('Z_Versandart')) {
        obj['Z_Versandart'] = ApiClient.convertToType(data['Z_Versandart'], 'String');
      }
      if (data.hasOwnProperty('Z_Versender_Referenz')) {
        obj['Z_Versender_Referenz'] = ApiClient.convertToType(data['Z_Versender_Referenz'], 'String');
      }
      if (data.hasOwnProperty('Z_Zuweiser')) {
        obj['Z_Zuweiser'] = ApiClient.convertToType(data['Z_Zuweiser'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} Z_Ablaufdatum
   */
  exports.prototype['Z_Ablaufdatum'] = undefined;
  /**
   * @member {String} Z_Behandlungsgrund
   */
  exports.prototype['Z_Behandlungsgrund'] = undefined;
  /**
   * @member {String} Z_Bemerkungen
   */
  exports.prototype['Z_Bemerkungen'] = undefined;
  /**
   * @member {String} Z_Benhandlungbeginn
   */
  exports.prototype['Z_Benhandlungbeginn'] = undefined;
  /**
   * @member {String} Z_Benhandlungende
   */
  exports.prototype['Z_Benhandlungende'] = undefined;
  /**
   * @member {String} Z_Diagnose
   */
  exports.prototype['Z_Diagnose'] = undefined;
  /**
   * @member {String} Z_Empf_nger_Referenz
   */
  exports.prototype['Z_Empf_nger_Referenz'] = undefined;
  /**
   * @member {String} Z_Gesetz
   */
  exports.prototype['Z_Gesetz'] = undefined;
  /**
   * @member {String} Z_Rolle
   */
  exports.prototype['Z_Rolle'] = undefined;
  /**
   * @member {String} Z_Standort
   */
  exports.prototype['Z_Standort'] = undefined;
  /**
   * @member {String} Z_Versandart
   */
  exports.prototype['Z_Versandart'] = undefined;
  /**
   * @member {String} Z_Versender_Referenz
   */
  exports.prototype['Z_Versender_Referenz'] = undefined;
  /**
   * @member {Number} Z_Zuweiser
   */
  exports.prototype['Z_Zuweiser'] = undefined;



  return exports;
}));


