/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProffixRestApiRequestSammlung);
  }
}(this, function(expect, ProffixRestApiRequestSammlung) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ADRNotizNotizNr', function() {
    it('should create an instance of ADRNotizNotizNr', function() {
      // uncomment below and update the code to test ADRNotizNotizNr
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be.a(ProffixRestApiRequestSammlung.ADRNotizNotizNr);
    });

    it('should have the property notizNr (base name: "NotizNr")', function() {
      // uncomment below and update the code to test the property notizNr
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property adresse (base name: "Adresse")', function() {
      // uncomment below and update the code to test the property adresse
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property kontakt (base name: "Kontakt")', function() {
      // uncomment below and update the code to test the property kontakt
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property mitarbeiter (base name: "Mitarbeiter")', function() {
      // uncomment below and update the code to test the property mitarbeiter
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property notizart (base name: "Notizart")', function() {
      // uncomment below and update the code to test the property notizart
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property datum (base name: "Datum")', function() {
      // uncomment below and update the code to test the property datum
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property termin (base name: "Termin")', function() {
      // uncomment below and update the code to test the property termin
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property notiz (base name: "Notiz")', function() {
      // uncomment below and update the code to test the property notiz
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property notizRTF (base name: "NotizRTF")', function() {
      // uncomment below and update the code to test the property notizRTF
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property erstelltAm (base name: "ErstelltAm")', function() {
      // uncomment below and update the code to test the property erstelltAm
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property erstelltVon (base name: "ErstelltVon")', function() {
      // uncomment below and update the code to test the property erstelltVon
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property geaendertAm (base name: "GeaendertAm")', function() {
      // uncomment below and update the code to test the property geaendertAm
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property geaendertVon (base name: "GeaendertVon")', function() {
      // uncomment below and update the code to test the property geaendertVon
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

    it('should have the property zusatzfelder (base name: "Zusatzfelder")', function() {
      // uncomment below and update the code to test the property zusatzfelder
      //var instance = new ProffixRestApiRequestSammlung.ADRNotizNotizNr();
      //expect(instance).to.be();
    });

  });

}));
