/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProffixRestApiRequestSammlung);
  }
}(this, function(expect, ProffixRestApiRequestSammlung) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EINWareneingangslisteWareneingangslisteNr', function() {
    it('should create an instance of EINWareneingangslisteWareneingangslisteNr', function() {
      // uncomment below and update the code to test EINWareneingangslisteWareneingangslisteNr
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be.a(ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr);
    });

    it('should have the property wareneingangslisteNr (base name: "WareneingangslisteNr")', function() {
      // uncomment below and update the code to test the property wareneingangslisteNr
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property adresse (base name: "Adresse")', function() {
      // uncomment below and update the code to test the property adresse
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property artikel (base name: "Artikel")', function() {
      // uncomment below and update the code to test the property artikel
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property bestellung (base name: "Bestellung")', function() {
      // uncomment below and update the code to test the property bestellung
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property datumBis (base name: "DatumBis")', function() {
      // uncomment below and update the code to test the property datumBis
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property datumVon (base name: "DatumVon")', function() {
      // uncomment below and update the code to test the property datumVon
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property eingangsdatum (base name: "Eingangsdatum")', function() {
      // uncomment below and update the code to test the property eingangsdatum
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property lagerort (base name: "Lagerort")', function() {
      // uncomment below and update the code to test the property lagerort
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property lagerplatz (base name: "Lagerplatz")', function() {
      // uncomment below and update the code to test the property lagerplatz
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "Total")', function() {
      // uncomment below and update the code to test the property total
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property verarbeitet (base name: "Verarbeitet")', function() {
      // uncomment below and update the code to test the property verarbeitet
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property erstelltAm (base name: "ErstelltAm")', function() {
      // uncomment below and update the code to test the property erstelltAm
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property erstelltVon (base name: "ErstelltVon")', function() {
      // uncomment below and update the code to test the property erstelltVon
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property geaendertAm (base name: "GeaendertAm")', function() {
      // uncomment below and update the code to test the property geaendertAm
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property geaendertVon (base name: "GeaendertVon")', function() {
      // uncomment below and update the code to test the property geaendertVon
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

    it('should have the property zusatzfelder (base name: "Zusatzfelder")', function() {
      // uncomment below and update the code to test the property zusatzfelder
      //var instance = new ProffixRestApiRequestSammlung.EINWareneingangslisteWareneingangslisteNr();
      //expect(instance).to.be();
    });

  });

}));
