/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProffixRestApiRequestSammlung);
  }
}(this, function(expect, ProffixRestApiRequestSammlung) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LAGBestellvorschlagRequest', function() {
    it('should create an instance of LAGBestellvorschlagRequest', function() {
      // uncomment below and update the code to test LAGBestellvorschlagRequest
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be.a(ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest);
    });

    it('should have the property artikel (base name: "Artikel")', function() {
      // uncomment below and update the code to test the property artikel
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property bestellpunkt (base name: "Bestellpunkt")', function() {
      // uncomment below and update the code to test the property bestellpunkt
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property bestellrhythmus (base name: "Bestellrhythmus")', function() {
      // uncomment below and update the code to test the property bestellrhythmus
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property bestellvorschlag (base name: "Bestellvorschlag")', function() {
      // uncomment below and update the code to test the property bestellvorschlag
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property artikelgruppe (base name: "Artikelgruppe")', function() {
      // uncomment below and update the code to test the property artikelgruppe
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property artikelklasse (base name: "Artikelklasse")', function() {
      // uncomment below and update the code to test the property artikelklasse
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property lagerort (base name: "Lagerort")', function() {
      // uncomment below and update the code to test the property lagerort
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property lieferadresse (base name: "Lieferadresse")', function() {
      // uncomment below and update the code to test the property lieferadresse
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property lieferantadresse (base name: "Lieferantadresse")', function() {
      // uncomment below and update the code to test the property lieferantadresse
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property maximum (base name: "Maximum")', function() {
      // uncomment below and update the code to test the property maximum
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property mindestbestellmenge (base name: "Mindestbestellmenge")', function() {
      // uncomment below and update the code to test the property mindestbestellmenge
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property minimum (base name: "Minimum")', function() {
      // uncomment below and update the code to test the property minimum
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property optimalbestellmenge (base name: "Optimalbestellmenge")', function() {
      // uncomment below and update the code to test the property optimalbestellmenge
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property sicherheitstage (base name: "Sicherheitstage")', function() {
      // uncomment below and update the code to test the property sicherheitstage
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

    it('should have the property wiederbeschaffung (base name: "Wiederbeschaffung")', function() {
      // uncomment below and update the code to test the property wiederbeschaffung
      //var instance = new ProffixRestApiRequestSammlung.LAGBestellvorschlagRequest();
      //expect(instance).to.be();
    });

  });

}));
