/**
 * PROFFIX REST API Request Sammlung
 * Dies ist eine Request-Sammlung der PROFFIX REST API, welche das PROFFIX REST API Entwicklerhandbuch unter [https://www.proffix.net/entwickler/restapi/handbuch](https://www.proffix.net/entwickler/restapi/handbuch) ergänzt.
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProffixRestApiRequestSammlung);
  }
}(this, function(expect, ProffixRestApiRequestSammlung) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PROKonditionKonditionNr', function() {
    it('should create an instance of PROKonditionKonditionNr', function() {
      // uncomment below and update the code to test PROKonditionKonditionNr
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be.a(ProffixRestApiRequestSammlung.PROKonditionKonditionNr);
    });

    it('should have the property konditionNr (base name: "KonditionNr")', function() {
      // uncomment below and update the code to test the property konditionNr
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property bezeichnung (base name: "Bezeichnung")', function() {
      // uncomment below and update the code to test the property bezeichnung
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property inaktiv (base name: "Inaktiv")', function() {
      // uncomment below and update the code to test the property inaktiv
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property endeJahr (base name: "EndeJahr")', function() {
      // uncomment below and update the code to test the property endeJahr
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property endeMonat (base name: "EndeMonat")', function() {
      // uncomment below and update the code to test the property endeMonat
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property endeQuartal (base name: "EndeQuartal")', function() {
      // uncomment below and update the code to test the property endeQuartal
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property nettoTage (base name: "NettoTage")', function() {
      // uncomment below and update the code to test the property nettoTage
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property skonto1Tage (base name: "Skonto1Tage")', function() {
      // uncomment below and update the code to test the property skonto1Tage
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property skonto1Prozent (base name: "Skonto1Prozent")', function() {
      // uncomment below and update the code to test the property skonto1Prozent
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property skonto2Tage (base name: "Skonto2Tage")', function() {
      // uncomment below and update the code to test the property skonto2Tage
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property skonto2Prozent (base name: "Skonto2Prozent")', function() {
      // uncomment below and update the code to test the property skonto2Prozent
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property erstelltAm (base name: "ErstelltAm")', function() {
      // uncomment below and update the code to test the property erstelltAm
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property erstelltVon (base name: "ErstelltVon")', function() {
      // uncomment below and update the code to test the property erstelltVon
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property geaendertAm (base name: "GeaendertAm")', function() {
      // uncomment below and update the code to test the property geaendertAm
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property geaendertVon (base name: "GeaendertVon")', function() {
      // uncomment below and update the code to test the property geaendertVon
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

    it('should have the property zusatzfelder (base name: "Zusatzfelder")', function() {
      // uncomment below and update the code to test the property zusatzfelder
      //var instance = new ProffixRestApiRequestSammlung.PROKonditionKonditionNr();
      //expect(instance).to.be();
    });

  });

}));
